---------------------------------------------
-- Title       : tb_SAD
-- Project     : Final project: SAD Calculation
---------------------------------------------
-- File        : tb_SAD.vhd
-- Language    : VHDL
-- Author(s)   : Francesco Urbani
-- Company     : 
-- Created     : Fri May 25 22:32:25 CEST 2018
---------------------------------------------
-- Description : Autogenerated test bench for SAD.vhd
---------------------------------------------
-- Update      :
---------------------------------------------

-- THIS TEST BENCH IS AUTOGENERATED FROM SAD_model.py
-- WARNING! All changes made in this file might be lost!



-- INPUTS:
-- N  = 8 bits
-- px = 16

-- SAD_bits_min := min num bits to correctly represent SAD
-- SAD_bits_min = ceil( log2( (2**N-1) * px**2 )) = 
--              = ceil( log2( 255 * 256 )) = 
--              = 16


-- PA = 
--     [227 133 242  97 108   2  32 201  14 254 107 229 100 117 200 195]
--     [ 42  51 140 191 216  12  96 173  69  15  30  20  98  60 191  47]
--     [ 80 126 106 193  45 191 100 150 237 188 121  50 179 109 131  55]
--     [ 12  20  30 157 114 168 176 202  10   0  89 101 139  57 203  88]
--     [ 97 153  66 171  15 136  52  67 140 230 210 234 237 121  64 251]
--     [245  68 240  54 247  88 126  79 110  77 245 154 216  52  50  57]
--     [116 227 249  45 227 238 231 122 192  56 227 179  24 153 161 152]
--     [210 225  29 173 101  44  93 207 226 251 122   6 101 146 124 116]
--     [117 117 198 183  21 254 158 200 252 252 172  79  59  58 155   8]
--     [206 180  43 216  61 182 155 143 144 250 146 192  87   5 213 134]
--     [ 45 153  60  49  21  18  71  85 148 232 112 161  28 121 222  60]
--     [231 192 201  55 100 166  81  51 120 182  37 117 182 141  15  42]
--     [ 37 132 136 201  90  79  25 143 211  68  32  47 187  46 154  55]
--     [190 124 217 194 101 209 168 251 145   6 121 218 205  24  71 232]
--     [ 33  49 140  82 245 181  43  91 129 233 214 114 196  66  65 111]
--     [ 18  87  10 250 190  19  15 174  96  20 175 246  13 199 194  72]
-- PB = 
--     [ 24 125  80  10 131 216  22 183 207 106 113  95 216 178 254 234]
--     [239 200 245  86 135 123 250  27 182 177 166 120  90 121 252  79]
--     [ 56  83 213  62   6  59   8  27 226 104  79  83 126 104  89  30]
--     [228  71 117   5 162  52  32 192 172 162  36 192  67 203 103 218]
--     [188   2  31  86  36 241 233 118 148  91 109 129  28 248  49  75]
--     [186 182 169  49 128  74  28 178   1 127 226  38  98 229   3 192]
--     [247  81  87 118 157 101 221 135 181 114  75 249 164  47 247  68]
--     [ 88   2 216  14   6 152  90  80 105  62   9 206 222 136  81 242]
--     [ 59  84  67 184  17  21 229 188  75 185 249  96 236 139 173  47]
--     [160 241 190 101 179 119 129 179  81  25 189 215 209 228  22 177]
--     [232  61   0  90 121 146 240  52 201  82  25 228  17  41 195 118]
--     [237 118  50  89  15  40  92 144 119 152 158 255   6 200  68 163]
--     [202  34 128 250  70 177 104 238 203  12  87 146 152  63 166 188]
--     [ 27 177  11  16  51 102 179  40 222 221  41 163 104  60  11 117]
--     [116 131 104 186 129 244   9  99 154   9 235 130  65  67  91 171]
--     [177  91 124  36  45  54 233 248   9  95 111 222 178 253 151  97]

-- OUTPUT:
-- DIFF = 
--     [203   8 162  87  23 214  10  18 193 148   6 134 116  61  54  39]
--     [197 149 105 105  81 111 154 146 113 162 136 100   8  61  61  32]
--     [ 24  43 107 131  39 132  92 123  11  84  42  33  53   5  42  25]
--     [216  51  87 152  48 116 144  10 162 162  53  91  72 146 100 130]
--     [ 91 151  35  85  21 105 181  51   8 139 101 105 209 127  15 176]
--     [ 59 114  71   5 119  14  98  99 109  50  19 116 118 177  47 135]
--     [131 146 162  73  70 137  10  13  11  58 152  70 140 106  86  84]
--     [122 223 187 159  95 108   3 127 121 189 113 200 121  10  43 126]
--     [ 58  33 131   1   4 233  71  12 177  67  77  17 177  81  18  39]
--     [ 46  61 147 115 118  63  26  36  63 225  43  23 122 223 191  43]
--     [187  92  60  41 100 128 169  33  53 150  87  67  11  80  27  58]
--     [  6  74 151  34  85 126  11  93   1  30 121 138 176  59  53 121]
--     [165  98   8  49  20  98  79  95   8  56  55  99  35  17  12 133]
--     [163  53 206 178  50 107  11 211  77 215  80  55 101  36  60 115]
--     [ 83  82  36 104 116  63  34   8  25 224  21  16 131   1  26  60]
--     [159   4 114 214 145  35 218  74  87  75  64  24 165  54  43  25]

-- SAD_value = sum(SAD) = 22907 = "0101100101111011"



library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;


entity tb_SAD is
end entity tb_SAD; -- tb_SAD


architecture struct of tb_SAD is
	
	component SAD is
		generic(
			Npixel     : positive := 16;      -- total # of pixels of the image
			
			Nbit       : positive := 8;        -- # of bits needed to represent the value of each pixel
			SAD_bits   : positive := 16 	-- # of bits needed to represent the output
		);
		port(
			CLK        : in  std_logic;
			RST        : in  std_logic;
			EN         : in  std_logic;
			PA         : in  std_logic_vector(Nbit-1  downto 0);
			PB         : in  std_logic_vector(Nbit-1  downto 0);
			
			SAD        : out std_logic_vector(SAD_bits-1 downto 0); 
			DATA_VALID : out std_logic
		);
	end component SAD;


	constant Npixel  : positive := 16;
	constant Nbit    : positive := 8;
	constant Mbit    : positive := 16;
	constant clk_per : time     := 5 ns;

	signal clk       : std_logic := '0';
	signal reset     : std_logic ;
	signal enable    : std_logic ;
	signal PA        : std_logic_vector(Nbit-1 downto 0) := "00000000";
	signal PB        : std_logic_vector(Nbit-1 downto 0) := "XXXXXXXX";
	
	signal testing   : Boolean   := True;




begin
	clk <= not clk after clk_per/2 when testing;-- ELSE '0';


	sad_i: SAD
		generic map(Npixel, Nbit, Mbit)
		port map(clk, reset, enable, PA, PB, open, open);


	drive_p: process
	  	begin
			
			
			wait for 23 ns;
			reset <= '1';
			enable <= '0';
			wait until rising_edge(clk);
			PB <= "00000000";
			wait for 40 ns;
			reset <= '0';
			wait until rising_edge(clk);
			enable <= '1';
			wait until rising_edge(clk);
			
			

			PA <= "11100011";
			PB <= "00011000";
			wait until rising_edge(clk);

			PA <= "10000101";
			PB <= "01111101";
			wait until rising_edge(clk);

			PA <= "11110010";
			PB <= "01010000";
			wait until rising_edge(clk);

			PA <= "01100001";
			PB <= "00001010";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "00000010";
			PB <= "11011000";
			wait until rising_edge(clk);

			PA <= "00100000";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "10110111";
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "11001111";
			wait until rising_edge(clk);

			PA <= "11111110";
			PB <= "01101010";
			wait until rising_edge(clk);

			PA <= "01101011";
			PB <= "01110001";
			wait until rising_edge(clk);

			PA <= "11100101";
			PB <= "01011111";
			wait until rising_edge(clk);

			PA <= "01100100";
			PB <= "11011000";
			wait until rising_edge(clk);

			PA <= "01110101";
			PB <= "10110010";
			wait until rising_edge(clk);

			PA <= "11001000";
			PB <= "11111110";
			wait until rising_edge(clk);

			PA <= "11000011";
			PB <= "11101010";
			wait until rising_edge(clk);

			PA <= "00101010";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "00110011";
			PB <= "11001000";
			wait until rising_edge(clk);

			PA <= "10001100";
			PB <= "11110101";
			wait until rising_edge(clk);

			PA <= "10111111";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "11011000";
			PB <= "10000111";
			wait until rising_edge(clk);

			PA <= "00001100";
			PB <= "01111011";
			wait until rising_edge(clk);

			PA <= "01100000";
			PB <= "11111010";
			wait until rising_edge(clk);

			PA <= "10101101";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "01000101";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "10110001";
			wait until rising_edge(clk);

			PA <= "00011110";
			PB <= "10100110";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "01111000";
			wait until rising_edge(clk);

			PA <= "01100010";
			PB <= "01011010";
			wait until rising_edge(clk);

			PA <= "00111100";
			PB <= "01111001";
			wait until rising_edge(clk);

			PA <= "10111111";
			PB <= "11111100";
			wait until rising_edge(clk);

			PA <= "00101111";
			PB <= "01001111";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "01111110";
			PB <= "01010011";
			wait until rising_edge(clk);

			PA <= "01101010";
			PB <= "11010101";
			wait until rising_edge(clk);

			PA <= "11000001";
			PB <= "00111110";
			wait until rising_edge(clk);

			PA <= "00101101";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "10111111";
			PB <= "00111011";
			wait until rising_edge(clk);

			PA <= "01100100";
			PB <= "00001000";
			wait until rising_edge(clk);

			PA <= "10010110";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "11101101";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "10111100";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "01001111";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "01010011";
			wait until rising_edge(clk);

			PA <= "10110011";
			PB <= "01111110";
			wait until rising_edge(clk);

			PA <= "01101101";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "10000011";
			PB <= "01011001";
			wait until rising_edge(clk);

			PA <= "00110111";
			PB <= "00011110";
			wait until rising_edge(clk);

			PA <= "00001100";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "01000111";
			wait until rising_edge(clk);

			PA <= "00011110";
			PB <= "01110101";
			wait until rising_edge(clk);

			PA <= "10011101";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "01110010";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "10101000";
			PB <= "00110100";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "00100000";
			wait until rising_edge(clk);

			PA <= "11001010";
			PB <= "11000000";
			wait until rising_edge(clk);

			PA <= "00001010";
			PB <= "10101100";
			wait until rising_edge(clk);

			PA <= "00000000";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "01011001";
			PB <= "00100100";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "11000000";
			wait until rising_edge(clk);

			PA <= "10001011";
			PB <= "01000011";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "11001011";
			wait until rising_edge(clk);

			PA <= "11001011";
			PB <= "01100111";
			wait until rising_edge(clk);

			PA <= "01011000";
			PB <= "11011010";
			wait until rising_edge(clk);

			PA <= "01100001";
			PB <= "10111100";
			wait until rising_edge(clk);

			PA <= "10011001";
			PB <= "00000010";
			wait until rising_edge(clk);

			PA <= "01000010";
			PB <= "00011111";
			wait until rising_edge(clk);

			PA <= "10101011";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "00100100";
			wait until rising_edge(clk);

			PA <= "10001000";
			PB <= "11110001";
			wait until rising_edge(clk);

			PA <= "00110100";
			PB <= "11101001";
			wait until rising_edge(clk);

			PA <= "01000011";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "10001100";
			PB <= "10010100";
			wait until rising_edge(clk);

			PA <= "11100110";
			PB <= "01011011";
			wait until rising_edge(clk);

			PA <= "11010010";
			PB <= "01101101";
			wait until rising_edge(clk);

			PA <= "11101010";
			PB <= "10000001";
			wait until rising_edge(clk);

			PA <= "11101101";
			PB <= "00011100";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "11111000";
			wait until rising_edge(clk);

			PA <= "01000000";
			PB <= "00110001";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "01001011";
			wait until rising_edge(clk);

			PA <= "11110101";
			PB <= "10111010";
			wait until rising_edge(clk);

			PA <= "01000100";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "11110000";
			PB <= "10101001";
			wait until rising_edge(clk);

			PA <= "00110110";
			PB <= "00110001";
			wait until rising_edge(clk);

			PA <= "11110111";
			PB <= "10000000";
			wait until rising_edge(clk);

			PA <= "01011000";
			PB <= "01001010";
			wait until rising_edge(clk);

			PA <= "01111110";
			PB <= "00011100";
			wait until rising_edge(clk);

			PA <= "01001111";
			PB <= "10110010";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "00000001";
			wait until rising_edge(clk);

			PA <= "01001101";
			PB <= "01111111";
			wait until rising_edge(clk);

			PA <= "11110101";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "10011010";
			PB <= "00100110";
			wait until rising_edge(clk);

			PA <= "11011000";
			PB <= "01100010";
			wait until rising_edge(clk);

			PA <= "00110100";
			PB <= "11100101";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "00000011";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "11000000";
			wait until rising_edge(clk);

			PA <= "01110100";
			PB <= "11110111";
			wait until rising_edge(clk);

			PA <= "11100011";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "11111001";
			PB <= "01010111";
			wait until rising_edge(clk);

			PA <= "00101101";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "11100011";
			PB <= "10011101";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "01100101";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "11011101";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "10000111";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "10110101";
			wait until rising_edge(clk);

			PA <= "00111000";
			PB <= "01110010";
			wait until rising_edge(clk);

			PA <= "11100011";
			PB <= "01001011";
			wait until rising_edge(clk);

			PA <= "10110011";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "00011000";
			PB <= "10100100";
			wait until rising_edge(clk);

			PA <= "10011001";
			PB <= "00101111";
			wait until rising_edge(clk);

			PA <= "10100001";
			PB <= "11110111";
			wait until rising_edge(clk);

			PA <= "10011000";
			PB <= "01000100";
			wait until rising_edge(clk);

			PA <= "11010010";
			PB <= "01011000";
			wait until rising_edge(clk);

			PA <= "11100001";
			PB <= "00000010";
			wait until rising_edge(clk);

			PA <= "00011101";
			PB <= "11011000";
			wait until rising_edge(clk);

			PA <= "10101101";
			PB <= "00001110";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "00101100";
			PB <= "10011000";
			wait until rising_edge(clk);

			PA <= "01011101";
			PB <= "01011010";
			wait until rising_edge(clk);

			PA <= "11001111";
			PB <= "01010000";
			wait until rising_edge(clk);

			PA <= "11100010";
			PB <= "01101001";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "00111110";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "11001110";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "10010010";
			PB <= "10001000";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "01110100";
			PB <= "11110010";
			wait until rising_edge(clk);

			PA <= "01110101";
			PB <= "00111011";
			wait until rising_edge(clk);

			PA <= "01110101";
			PB <= "01010100";
			wait until rising_edge(clk);

			PA <= "11000110";
			PB <= "01000011";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "10111000";
			wait until rising_edge(clk);

			PA <= "00010101";
			PB <= "00010001";
			wait until rising_edge(clk);

			PA <= "11111110";
			PB <= "00010101";
			wait until rising_edge(clk);

			PA <= "10011110";
			PB <= "11100101";
			wait until rising_edge(clk);

			PA <= "11001000";
			PB <= "10111100";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "01001011";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "10111001";
			wait until rising_edge(clk);

			PA <= "10101100";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "01001111";
			PB <= "01100000";
			wait until rising_edge(clk);

			PA <= "00111011";
			PB <= "11101100";
			wait until rising_edge(clk);

			PA <= "00111010";
			PB <= "10001011";
			wait until rising_edge(clk);

			PA <= "10011011";
			PB <= "10101101";
			wait until rising_edge(clk);

			PA <= "00001000";
			PB <= "00101111";
			wait until rising_edge(clk);

			PA <= "11001110";
			PB <= "10100000";
			wait until rising_edge(clk);

			PA <= "10110100";
			PB <= "11110001";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "10111110";
			wait until rising_edge(clk);

			PA <= "11011000";
			PB <= "01100101";
			wait until rising_edge(clk);

			PA <= "00111101";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "10110110";
			PB <= "01110111";
			wait until rising_edge(clk);

			PA <= "10011011";
			PB <= "10000001";
			wait until rising_edge(clk);

			PA <= "10001111";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "10010000";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "10010010";
			PB <= "10111101";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "01010111";
			PB <= "11010001";
			wait until rising_edge(clk);

			PA <= "00000101";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "11010101";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "10000110";
			PB <= "10110001";
			wait until rising_edge(clk);

			PA <= "00101101";
			PB <= "11101000";
			wait until rising_edge(clk);

			PA <= "10011001";
			PB <= "00111101";
			wait until rising_edge(clk);

			PA <= "00111100";
			PB <= "00000000";
			wait until rising_edge(clk);

			PA <= "00110001";
			PB <= "01011010";
			wait until rising_edge(clk);

			PA <= "00010101";
			PB <= "01111001";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "10010010";
			wait until rising_edge(clk);

			PA <= "01000111";
			PB <= "11110000";
			wait until rising_edge(clk);

			PA <= "01010101";
			PB <= "00110100";
			wait until rising_edge(clk);

			PA <= "10010100";
			PB <= "11001001";
			wait until rising_edge(clk);

			PA <= "11101000";
			PB <= "01010010";
			wait until rising_edge(clk);

			PA <= "01110000";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "10100001";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "00011100";
			PB <= "00010001";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "00101001";
			wait until rising_edge(clk);

			PA <= "11011110";
			PB <= "11000011";
			wait until rising_edge(clk);

			PA <= "00111100";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "11101101";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "00110010";
			wait until rising_edge(clk);

			PA <= "00110111";
			PB <= "01011001";
			wait until rising_edge(clk);

			PA <= "01100100";
			PB <= "00001111";
			wait until rising_edge(clk);

			PA <= "10100110";
			PB <= "00101000";
			wait until rising_edge(clk);

			PA <= "01010001";
			PB <= "01011100";
			wait until rising_edge(clk);

			PA <= "00110011";
			PB <= "10010000";
			wait until rising_edge(clk);

			PA <= "01111000";
			PB <= "01110111";
			wait until rising_edge(clk);

			PA <= "10110110";
			PB <= "10011000";
			wait until rising_edge(clk);

			PA <= "00100101";
			PB <= "10011110";
			wait until rising_edge(clk);

			PA <= "01110101";
			PB <= "11111111";
			wait until rising_edge(clk);

			PA <= "10110110";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "10001101";
			PB <= "11001000";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "01000100";
			wait until rising_edge(clk);

			PA <= "00101010";
			PB <= "10100011";
			wait until rising_edge(clk);

			PA <= "00100101";
			PB <= "11001010";
			wait until rising_edge(clk);

			PA <= "10000100";
			PB <= "00100010";
			wait until rising_edge(clk);

			PA <= "10001000";
			PB <= "10000000";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "11111010";
			wait until rising_edge(clk);

			PA <= "01011010";
			PB <= "01000110";
			wait until rising_edge(clk);

			PA <= "01001111";
			PB <= "10110001";
			wait until rising_edge(clk);

			PA <= "00011001";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "10001111";
			PB <= "11101110";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "11001011";
			wait until rising_edge(clk);

			PA <= "01000100";
			PB <= "00001100";
			wait until rising_edge(clk);

			PA <= "00100000";
			PB <= "01010111";
			wait until rising_edge(clk);

			PA <= "00101111";
			PB <= "10010010";
			wait until rising_edge(clk);

			PA <= "10111011";
			PB <= "10011000";
			wait until rising_edge(clk);

			PA <= "00101110";
			PB <= "00111111";
			wait until rising_edge(clk);

			PA <= "10011010";
			PB <= "10100110";
			wait until rising_edge(clk);

			PA <= "00110111";
			PB <= "10111100";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "10110001";
			wait until rising_edge(clk);

			PA <= "11011001";
			PB <= "00001011";
			wait until rising_edge(clk);

			PA <= "11000010";
			PB <= "00010000";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "00110011";
			wait until rising_edge(clk);

			PA <= "11010001";
			PB <= "01100110";
			wait until rising_edge(clk);

			PA <= "10101000";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "00101000";
			wait until rising_edge(clk);

			PA <= "10010001";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "11011101";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "00101001";
			wait until rising_edge(clk);

			PA <= "11011010";
			PB <= "10100011";
			wait until rising_edge(clk);

			PA <= "11001101";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "00011000";
			PB <= "00111100";
			wait until rising_edge(clk);

			PA <= "01000111";
			PB <= "00001011";
			wait until rising_edge(clk);

			PA <= "11101000";
			PB <= "01110101";
			wait until rising_edge(clk);

			PA <= "00100001";
			PB <= "01110100";
			wait until rising_edge(clk);

			PA <= "00110001";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "10001100";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "01010010";
			PB <= "10111010";
			wait until rising_edge(clk);

			PA <= "11110101";
			PB <= "10000001";
			wait until rising_edge(clk);

			PA <= "10110101";
			PB <= "11110100";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "01100011";
			wait until rising_edge(clk);

			PA <= "10000001";
			PB <= "10011010";
			wait until rising_edge(clk);

			PA <= "11101001";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "11010110";
			PB <= "11101011";
			wait until rising_edge(clk);

			PA <= "01110010";
			PB <= "10000010";
			wait until rising_edge(clk);

			PA <= "11000100";
			PB <= "01000001";
			wait until rising_edge(clk);

			PA <= "01000010";
			PB <= "01000011";
			wait until rising_edge(clk);

			PA <= "01000001";
			PB <= "01011011";
			wait until rising_edge(clk);

			PA <= "01101111";
			PB <= "10101011";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "10110001";
			wait until rising_edge(clk);

			PA <= "01010111";
			PB <= "01011011";
			wait until rising_edge(clk);

			PA <= "00001010";
			PB <= "01111100";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "00100100";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "00010011";
			PB <= "00110110";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "11101001";
			wait until rising_edge(clk);

			PA <= "10101110";
			PB <= "11111000";
			wait until rising_edge(clk);

			PA <= "01100000";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "01011111";
			wait until rising_edge(clk);

			PA <= "10101111";
			PB <= "01101111";
			wait until rising_edge(clk);

			PA <= "11110110";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "00001101";
			PB <= "10110010";
			wait until rising_edge(clk);

			PA <= "11000111";
			PB <= "11111101";
			wait until rising_edge(clk);

			PA <= "11000010";
			PB <= "10010111";
			wait until rising_edge(clk);

			PA <= "01001000";
			PB <= "01100001";
			wait until rising_edge(clk);
			----------------------------------------
			wait for 50 ns;
			reset <= '1';
			wait for 72 ns;
			reset <='0';
			
			----------------------------------------

			PA <= "11100011";
			PB <= "00011000";
			wait until rising_edge(clk);


			PA <= "10000101";
			PB <= "01111101";
			wait until rising_edge(clk);


			PA <= "11110010";
			PB <= "01010000";
			wait until rising_edge(clk);


			PA <= "01100001";
			PB <= "00001010";
			wait until rising_edge(clk);


			PA <= "01101100";
			PB <= "10000011";
			wait until rising_edge(clk);


			PA <= "00000010";
			PB <= "11011000";
			wait until rising_edge(clk);


			PA <= "00100000";
			PB <= "00010110";
			wait until rising_edge(clk);


			PA <= "11001001";
			PB <= "10110111";
			wait until rising_edge(clk);


			PA <= "00001110";
			PB <= "11001111";
			wait until rising_edge(clk);


			PA <= "11111110";
			PB <= "01101010";
			wait until rising_edge(clk);


			PA <= "01101011";
			PB <= "01110001";
			wait until rising_edge(clk);


			PA <= "11100101";
			PB <= "01011111";
			wait until rising_edge(clk);


			PA <= "01100100";
			PB <= "11011000";
			wait until rising_edge(clk);


			PA <= "01110101";
			PB <= "10110010";
			wait until rising_edge(clk);


			PA <= "11001000";
			PB <= "11111110";
			wait until rising_edge(clk);


			PA <= "11000011";
			PB <= "11101010";
			wait until rising_edge(clk);


			PA <= "00101010";
			PB <= "11101111";
			wait until rising_edge(clk);


			PA <= "00110011";
			PB <= "11001000";
			wait until rising_edge(clk);


			PA <= "10001100";
			PB <= "11110101";
			wait until rising_edge(clk);


			PA <= "10111111";
			PB <= "01010110";
			wait until rising_edge(clk);


			PA <= "11011000";
			PB <= "10000111";
			wait until rising_edge(clk);


			PA <= "00001100";
			PB <= "01111011";
			wait until rising_edge(clk);


			PA <= "01100000";
			PB <= "11111010";
			wait until rising_edge(clk);


			PA <= "10101101";
			PB <= "00011011";
			wait until rising_edge(clk);


			PA <= "01000101";
			PB <= "10110110";
			wait until rising_edge(clk);


			enable <= '0';
			PA <= "00001111";
			PB <= "10110001";
			wait until rising_edge(clk);


			PA <= "00011110";
			PB <= "10100110";
			wait until rising_edge(clk);


			PA <= "00010100";
			PB <= "01111000";
			wait until rising_edge(clk);


			PA <= "01100010";
			PB <= "01011010";
			wait until rising_edge(clk);


			PA <= "00111100";
			PB <= "01111001";
			wait until rising_edge(clk);


			PA <= "10111111";
			PB <= "11111100";
			wait until rising_edge(clk);


			PA <= "00101111";
			PB <= "01001111";
			wait until rising_edge(clk);


			PA <= "01010000";
			PB <= "00111000";
			wait until rising_edge(clk);


			PA <= "01111110";
			PB <= "01010011";
			wait until rising_edge(clk);


			PA <= "01101010";
			PB <= "11010101";
			wait until rising_edge(clk);


			PA <= "11000001";
			PB <= "00111110";
			wait until rising_edge(clk);


			PA <= "00101101";
			PB <= "00000110";
			wait until rising_edge(clk);


			PA <= "10111111";
			PB <= "00111011";
			wait until rising_edge(clk);


			PA <= "01100100";
			PB <= "00001000";
			wait until rising_edge(clk);


			PA <= "10010110";
			PB <= "00011011";
			wait until rising_edge(clk);


			PA <= "11101101";
			PB <= "11100010";
			wait until rising_edge(clk);


			PA <= "10111100";
			PB <= "01101000";
			wait until rising_edge(clk);


			PA <= "01111001";
			PB <= "01001111";
			wait until rising_edge(clk);


			PA <= "00110010";
			PB <= "01010011";
			wait until rising_edge(clk);


			PA <= "10110011";
			PB <= "01111110";
			wait until rising_edge(clk);


			PA <= "01101101";
			PB <= "01101000";
			wait until rising_edge(clk);


			PA <= "10000011";
			PB <= "01011001";
			wait until rising_edge(clk);


			PA <= "00110111";
			PB <= "00011110";
			wait until rising_edge(clk);


			PA <= "00001100";
			PB <= "11100100";
			wait until rising_edge(clk);


			PA <= "00010100";
			PB <= "01000111";
			wait until rising_edge(clk);


			PA <= "00011110";
			PB <= "01110101";
			wait until rising_edge(clk);


			enable <= '1';
			PA <= "10011101";
			PB <= "00000101";
			wait until rising_edge(clk);


			PA <= "01110010";
			PB <= "10100010";
			wait until rising_edge(clk);


			PA <= "10101000";
			PB <= "00110100";
			wait until rising_edge(clk);


			PA <= "10110000";
			PB <= "00100000";
			wait until rising_edge(clk);


			PA <= "11001010";
			PB <= "11000000";
			wait until rising_edge(clk);


			PA <= "00001010";
			PB <= "10101100";
			wait until rising_edge(clk);


			PA <= "00000000";
			PB <= "10100010";
			wait until rising_edge(clk);


			PA <= "01011001";
			PB <= "00100100";
			wait until rising_edge(clk);


			PA <= "01100101";
			PB <= "11000000";
			wait until rising_edge(clk);


			PA <= "10001011";
			PB <= "01000011";
			wait until rising_edge(clk);


			PA <= "00111001";
			PB <= "11001011";
			wait until rising_edge(clk);


			PA <= "11001011";
			PB <= "01100111";
			wait until rising_edge(clk);


			PA <= "01011000";
			PB <= "11011010";
			wait until rising_edge(clk);


			PA <= "01100001";
			PB <= "10111100";
			wait until rising_edge(clk);


			PA <= "10011001";
			PB <= "00000010";
			wait until rising_edge(clk);


			PA <= "01000010";
			PB <= "00011111";
			wait until rising_edge(clk);


			PA <= "10101011";
			PB <= "01010110";
			wait until rising_edge(clk);


			PA <= "00001111";
			PB <= "00100100";
			wait until rising_edge(clk);


			PA <= "10001000";
			PB <= "11110001";
			wait until rising_edge(clk);


			PA <= "00110100";
			PB <= "11101001";
			wait until rising_edge(clk);


			PA <= "01000011";
			PB <= "01110110";
			wait until rising_edge(clk);


			PA <= "10001100";
			PB <= "10010100";
			wait until rising_edge(clk);


			PA <= "11100110";
			PB <= "01011011";
			wait until rising_edge(clk);


			PA <= "11010010";
			PB <= "01101101";
			wait until rising_edge(clk);


			PA <= "11101010";
			PB <= "10000001";
			wait until rising_edge(clk);


			PA <= "11101101";
			PB <= "00011100";
			wait until rising_edge(clk);


			PA <= "01111001";
			PB <= "11111000";
			wait until rising_edge(clk);


			PA <= "01000000";
			PB <= "00110001";
			wait until rising_edge(clk);


			PA <= "11111011";
			PB <= "01001011";
			wait until rising_edge(clk);


			PA <= "11110101";
			PB <= "10111010";
			wait until rising_edge(clk);


			PA <= "01000100";
			PB <= "10110110";
			wait until rising_edge(clk);


			PA <= "11110000";
			PB <= "10101001";
			wait until rising_edge(clk);


			PA <= "00110110";
			PB <= "00110001";
			wait until rising_edge(clk);


			PA <= "11110111";
			PB <= "10000000";
			wait until rising_edge(clk);


			PA <= "01011000";
			PB <= "01001010";
			wait until rising_edge(clk);


			PA <= "01111110";
			PB <= "00011100";
			wait until rising_edge(clk);


			PA <= "01001111";
			PB <= "10110010";
			wait until rising_edge(clk);


			PA <= "01101110";
			PB <= "00000001";
			wait until rising_edge(clk);


			PA <= "01001101";
			PB <= "01111111";
			wait until rising_edge(clk);


			PA <= "11110101";
			PB <= "11100010";
			wait until rising_edge(clk);


			PA <= "10011010";
			PB <= "00100110";
			wait until rising_edge(clk);


			PA <= "11011000";
			PB <= "01100010";
			wait until rising_edge(clk);


			PA <= "00110100";
			PB <= "11100101";
			wait until rising_edge(clk);


			PA <= "00110010";
			PB <= "00000011";
			wait until rising_edge(clk);


			PA <= "00111001";
			PB <= "11000000";
			wait until rising_edge(clk);


			PA <= "01110100";
			PB <= "11110111";
			wait until rising_edge(clk);


			PA <= "11100011";
			PB <= "01010001";
			wait until rising_edge(clk);


			PA <= "11111001";
			PB <= "01010111";
			wait until rising_edge(clk);


			PA <= "00101101";
			PB <= "01110110";
			wait until rising_edge(clk);


			PA <= "11100011";
			PB <= "10011101";
			wait until rising_edge(clk);


			PA <= "11101110";
			PB <= "01100101";
			wait until rising_edge(clk);


			reset <= '1';
			PA <= "11100111";
			PB <= "11011101";
			wait until rising_edge(clk);


			PA <= "01111010";
			PB <= "10000111";
			wait until rising_edge(clk);


			PA <= "11000000";
			PB <= "10110101";
			wait until rising_edge(clk);


			PA <= "00111000";
			PB <= "01110010";
			wait until rising_edge(clk);


			PA <= "11100011";
			PB <= "01001011";
			wait until rising_edge(clk);


			reset <= '0';
			PA <= "10110011";
			PB <= "11111001";
			wait until rising_edge(clk);


			PA <= "00011000";
			PB <= "10100100";
			wait until rising_edge(clk);


			PA <= "10011001";
			PB <= "00101111";
			wait until rising_edge(clk);


			PA <= "10100001";
			PB <= "11110111";
			wait until rising_edge(clk);


			PA <= "10011000";
			PB <= "01000100";
			wait until rising_edge(clk);


			PA <= "11010010";
			PB <= "01011000";
			wait until rising_edge(clk);


			PA <= "11100001";
			PB <= "00000010";
			wait until rising_edge(clk);


			PA <= "00011101";
			PB <= "11011000";
			wait until rising_edge(clk);


			PA <= "10101101";
			PB <= "00001110";
			wait until rising_edge(clk);


			PA <= "01100101";
			PB <= "00000110";
			wait until rising_edge(clk);


			PA <= "00101100";
			PB <= "10011000";
			wait until rising_edge(clk);


			PA <= "01011101";
			PB <= "01011010";
			wait until rising_edge(clk);


			PA <= "11001111";
			PB <= "01010000";
			wait until rising_edge(clk);


			PA <= "11100010";
			PB <= "01101001";
			wait until rising_edge(clk);


			PA <= "11111011";
			PB <= "00111110";
			wait until rising_edge(clk);


			PA <= "01111010";
			PB <= "00001001";
			wait until rising_edge(clk);


			PA <= "00000110";
			PB <= "11001110";
			wait until rising_edge(clk);


			PA <= "01100101";
			PB <= "11011110";
			wait until rising_edge(clk);


			PA <= "10010010";
			PB <= "10001000";
			wait until rising_edge(clk);


			PA <= "01111100";
			PB <= "01010001";
			wait until rising_edge(clk);


			PA <= "01110100";
			PB <= "11110010";
			wait until rising_edge(clk);


			PA <= "01110101";
			PB <= "00111011";
			wait until rising_edge(clk);


			PA <= "01110101";
			PB <= "01010100";
			wait until rising_edge(clk);


			PA <= "11000110";
			PB <= "01000011";
			wait until rising_edge(clk);


			PA <= "10110111";
			PB <= "10111000";
			wait until rising_edge(clk);


			PA <= "00010101";
			PB <= "00010001";
			wait until rising_edge(clk);


			PA <= "11111110";
			PB <= "00010101";
			wait until rising_edge(clk);


			PA <= "10011110";
			PB <= "11100101";
			wait until rising_edge(clk);


			PA <= "11001000";
			PB <= "10111100";
			wait until rising_edge(clk);


			PA <= "11111100";
			PB <= "01001011";
			wait until rising_edge(clk);


			PA <= "11111100";
			PB <= "10111001";
			wait until rising_edge(clk);


			PA <= "10101100";
			PB <= "11111001";
			wait until rising_edge(clk);


			PA <= "01001111";
			PB <= "01100000";
			wait until rising_edge(clk);


			PA <= "00111011";
			PB <= "11101100";
			wait until rising_edge(clk);


			PA <= "00111010";
			PB <= "10001011";
			wait until rising_edge(clk);


			PA <= "10011011";
			PB <= "10101101";
			wait until rising_edge(clk);


			PA <= "00001000";
			PB <= "00101111";
			wait until rising_edge(clk);


			PA <= "11001110";
			PB <= "10100000";
			wait until rising_edge(clk);


			PA <= "10110100";
			PB <= "11110001";
			wait until rising_edge(clk);


			PA <= "00101011";
			PB <= "10111110";
			wait until rising_edge(clk);


			PA <= "11011000";
			PB <= "01100101";
			wait until rising_edge(clk);


			PA <= "00111101";
			PB <= "10110011";
			wait until rising_edge(clk);


			PA <= "10110110";
			PB <= "01110111";
			wait until rising_edge(clk);


			PA <= "10011011";
			PB <= "10000001";
			wait until rising_edge(clk);


			PA <= "10001111";
			PB <= "10110011";
			wait until rising_edge(clk);


			PA <= "10010000";
			PB <= "01010001";
			wait until rising_edge(clk);


			PA <= "11111010";
			PB <= "00011001";
			wait until rising_edge(clk);


			PA <= "10010010";
			PB <= "10111101";
			wait until rising_edge(clk);


			PA <= "11000000";
			PB <= "11010111";
			wait until rising_edge(clk);


			PA <= "01010111";
			PB <= "11010001";
			wait until rising_edge(clk);


			PA <= "00000101";
			PB <= "11100100";
			wait until rising_edge(clk);


			PA <= "11010101";
			PB <= "00010110";
			wait until rising_edge(clk);


			PA <= "10000110";
			PB <= "10110001";
			wait until rising_edge(clk);


			PA <= "00101101";
			PB <= "11101000";
			wait until rising_edge(clk);


			PA <= "10011001";
			PB <= "00111101";
			wait until rising_edge(clk);


			PA <= "00111100";
			PB <= "00000000";
			wait until rising_edge(clk);


			PA <= "00110001";
			PB <= "01011010";
			wait until rising_edge(clk);


			PA <= "00010101";
			PB <= "01111001";
			wait until rising_edge(clk);


			PA <= "00010010";
			PB <= "10010010";
			wait until rising_edge(clk);


			PA <= "01000111";
			PB <= "11110000";
			wait until rising_edge(clk);


			PA <= "01010101";
			PB <= "00110100";
			wait until rising_edge(clk);


			PA <= "10010100";
			PB <= "11001001";
			wait until rising_edge(clk);


			PA <= "11101000";
			PB <= "01010010";
			wait until rising_edge(clk);


			PA <= "01110000";
			PB <= "00011001";
			wait until rising_edge(clk);


			PA <= "10100001";
			PB <= "11100100";
			wait until rising_edge(clk);


			PA <= "00011100";
			PB <= "00010001";
			wait until rising_edge(clk);


			PA <= "01111001";
			PB <= "00101001";
			wait until rising_edge(clk);


			PA <= "11011110";
			PB <= "11000011";
			wait until rising_edge(clk);


			PA <= "00111100";
			PB <= "01110110";
			wait until rising_edge(clk);


			PA <= "11100111";
			PB <= "11101101";
			wait until rising_edge(clk);


			PA <= "11000000";
			PB <= "01110110";
			wait until rising_edge(clk);


			PA <= "11001001";
			PB <= "00110010";
			wait until rising_edge(clk);


			PA <= "00110111";
			PB <= "01011001";
			wait until rising_edge(clk);


			PA <= "01100100";
			PB <= "00001111";
			wait until rising_edge(clk);


			PA <= "10100110";
			PB <= "00101000";
			wait until rising_edge(clk);


			PA <= "01010001";
			PB <= "01011100";
			wait until rising_edge(clk);


			PA <= "00110011";
			PB <= "10010000";
			wait until rising_edge(clk);


			PA <= "01111000";
			PB <= "01110111";
			wait until rising_edge(clk);


			PA <= "10110110";
			PB <= "10011000";
			wait until rising_edge(clk);


			PA <= "00100101";
			PB <= "10011110";
			wait until rising_edge(clk);


			PA <= "01110101";
			PB <= "11111111";
			wait until rising_edge(clk);


			PA <= "10110110";
			PB <= "00000110";
			wait until rising_edge(clk);


			PA <= "10001101";
			PB <= "11001000";
			wait until rising_edge(clk);


			PA <= "00001111";
			PB <= "01000100";
			wait until rising_edge(clk);


			PA <= "00101010";
			PB <= "10100011";
			wait until rising_edge(clk);


			PA <= "00100101";
			PB <= "11001010";
			wait until rising_edge(clk);


			PA <= "10000100";
			PB <= "00100010";
			wait until rising_edge(clk);


			PA <= "10001000";
			PB <= "10000000";
			wait until rising_edge(clk);


			PA <= "11001001";
			PB <= "11111010";
			wait until rising_edge(clk);


			PA <= "01011010";
			PB <= "01000110";
			wait until rising_edge(clk);


			PA <= "01001111";
			PB <= "10110001";
			wait until rising_edge(clk);


			PA <= "00011001";
			PB <= "01101000";
			wait until rising_edge(clk);


			PA <= "10001111";
			PB <= "11101110";
			wait until rising_edge(clk);


			PA <= "11010011";
			PB <= "11001011";
			wait until rising_edge(clk);


			PA <= "01000100";
			PB <= "00001100";
			wait until rising_edge(clk);


			PA <= "00100000";
			PB <= "01010111";
			wait until rising_edge(clk);


			PA <= "00101111";
			PB <= "10010010";
			wait until rising_edge(clk);


			PA <= "10111011";
			PB <= "10011000";
			wait until rising_edge(clk);


			PA <= "00101110";
			PB <= "00111111";
			wait until rising_edge(clk);


			PA <= "10011010";
			PB <= "10100110";
			wait until rising_edge(clk);


			PA <= "00110111";
			PB <= "10111100";
			wait until rising_edge(clk);


			PA <= "10111110";
			PB <= "00011011";
			wait until rising_edge(clk);


			PA <= "01111100";
			PB <= "10110001";
			wait until rising_edge(clk);


			PA <= "11011001";
			PB <= "00001011";
			wait until rising_edge(clk);


			PA <= "11000010";
			PB <= "00010000";
			wait until rising_edge(clk);


			PA <= "01100101";
			PB <= "00110011";
			wait until rising_edge(clk);


			PA <= "11010001";
			PB <= "01100110";
			wait until rising_edge(clk);


			PA <= "10101000";
			PB <= "10110011";
			wait until rising_edge(clk);


			PA <= "11111011";
			PB <= "00101000";
			wait until rising_edge(clk);


			PA <= "10010001";
			PB <= "11011110";
			wait until rising_edge(clk);


			PA <= "00000110";
			PB <= "11011101";
			wait until rising_edge(clk);


			PA <= "01111001";
			PB <= "00101001";
			wait until rising_edge(clk);


			PA <= "11011010";
			PB <= "10100011";
			wait until rising_edge(clk);


			PA <= "11001101";
			PB <= "01101000";
			wait until rising_edge(clk);


			PA <= "00011000";
			PB <= "00111100";
			wait until rising_edge(clk);


			PA <= "01000111";
			PB <= "00001011";
			wait until rising_edge(clk);


			PA <= "11101000";
			PB <= "01110101";
			wait until rising_edge(clk);


			PA <= "00100001";
			PB <= "01110100";
			wait until rising_edge(clk);


			PA <= "00110001";
			PB <= "10000011";
			wait until rising_edge(clk);


			PA <= "10001100";
			PB <= "01101000";
			wait until rising_edge(clk);


			PA <= "01010010";
			PB <= "10111010";
			wait until rising_edge(clk);


			PA <= "11110101";
			PB <= "10000001";
			wait until rising_edge(clk);


			PA <= "10110101";
			PB <= "11110100";
			wait until rising_edge(clk);


			PA <= "00101011";
			PB <= "00001001";
			wait until rising_edge(clk);


			PA <= "01011011";
			PB <= "01100011";
			wait until rising_edge(clk);


			PA <= "10000001";
			PB <= "10011010";
			wait until rising_edge(clk);


			PA <= "11101001";
			PB <= "00001001";
			wait until rising_edge(clk);


			PA <= "11010110";
			PB <= "11101011";
			wait until rising_edge(clk);


			PA <= "01110010";
			PB <= "10000010";
			wait until rising_edge(clk);


			PA <= "11000100";
			PB <= "01000001";
			wait until rising_edge(clk);


			PA <= "01000010";
			PB <= "01000011";
			wait until rising_edge(clk);


			PA <= "01000001";
			PB <= "01011011";
			wait until rising_edge(clk);


			PA <= "01101111";
			PB <= "10101011";
			wait until rising_edge(clk);


			PA <= "00010010";
			PB <= "10110001";
			wait until rising_edge(clk);


			PA <= "01010111";
			PB <= "01011011";
			wait until rising_edge(clk);


			PA <= "00001010";
			PB <= "01111100";
			wait until rising_edge(clk);


			PA <= "11111010";
			PB <= "00100100";
			wait until rising_edge(clk);


			PA <= "10111110";
			PB <= "00101101";
			wait until rising_edge(clk);


			PA <= "00010011";
			PB <= "00110110";
			wait until rising_edge(clk);


			PA <= "00001111";
			PB <= "11101001";
			wait until rising_edge(clk);


			PA <= "10101110";
			PB <= "11111000";
			wait until rising_edge(clk);


			PA <= "01100000";
			PB <= "00001001";
			wait until rising_edge(clk);


			PA <= "00010100";
			PB <= "01011111";
			wait until rising_edge(clk);


			PA <= "10101111";
			PB <= "01101111";
			wait until rising_edge(clk);


			PA <= "11110110";
			PB <= "11011110";
			wait until rising_edge(clk);


			PA <= "00001101";
			PB <= "10110010";
			wait until rising_edge(clk);


			PA <= "11000111";
			PB <= "11111101";
			wait until rising_edge(clk);


			PA <= "11000010";
			PB <= "10010111";
			wait until rising_edge(clk);


			PA <= "01001000";
			PB <= "01100001";
			wait until rising_edge(clk);


			----------------------------------


	  		wait for 190 ns;
	  		testing <= False;
	  		wait;
	  	end process;

	  	--drive_rst: process
	  	--begin
	  	--	wait for 80 ns;
	    --	reset <= '1';
	  	--	wait for 40 ns;
	  	--	reset <= '0';
	  	--	wait until rising_edge(clk);
	  	--	wait;
	  	--end process;


	  	--drive_en : process
	  	--begin
  		--	wait for 44 ns;
	  	--	enable <= '1';
	  	--	wait for 89 ns;
	  	--	enable <= '0';
	  	--	wait for 71 ns;
		--	enable <= '1';
	  	--	wait for 1111 ns;
	  	--	wait;
	  	--end process;

end architecture;

