---------------------------------------------
-- Title       : tb_SAD
-- Project     : Final project: SAD Calculation
---------------------------------------------
-- File        : tb_SAD.vhd
-- Language    : VHDL
-- Author(s)   : Francesco Urbani
-- Company     : 
-- Created     : Wed May 23 18:13:48 CEST 2018
---------------------------------------------
-- Description : Autogenerated test bench for SAD.vhd
---------------------------------------------
-- Update      :
---------------------------------------------

-- THIS TEST BENCH IS AUTOGENERATED FROM SAD_model.py
-- WARNING! All changes made in this file might be lost!



-- INPUTS:
-- N  = 8 bit
-- px = 16

-- M_min := min num bits to correctly represent SAD
-- M_min = ceil( log2( (2**N-1) * px**2 )) = 
--       = ceil( log2( 255 * 256 )) = 
--       = 16


-- PA = 
--     [ 14 144  14  35 133  91 212 136  87 112 173 207 128  54 112 147]
--     [190 110  57 251 107 204  99 130  91 174  73 183 122 184  32 188]
--     [235 238 198  33 162 108 208 109  50  62 244 176  63 238 222  27]
--     [132  23  25 102 212  48  63  25  83  83  91  49 196 192 110 236]
--     [ 94 211  80 201  71  41  51 252 149 254 250 246 212 151 220  29]
--     [160 141 230  43  16  37  34 211  95 239 211   6  58 108 142 164]
--     [183  90 138  59  50 255  76  73  77 110 231 105   2 238 162 199]
--     [176 192 122 229 219 152  80 202 234  76  62 187  20  67  11 210]
--     [137  43  76 224  95  18  95 147 252  84 249 146 161 102  78  91]
--     [211  57 131  93  97 156  92 121  84 239  83 176 124  80  26 225]
--     [ 98  63 228 190 224  48 243 147  30 111  92 209 239 231 213  79]
--     [ 60 126 182  31  20 131 119 130  15 174 163 221  72  83 251  40]
--     [227  90 193 175 101 177  73 200 252 108  33  45 120 151   6  73]
--     [229 201 162 228 240  86 107 115 217  18 203 153 219 102 108 250]
--     [140 115  92  70  56  31 106 121  21 252 187 162   3 120 105 175]
--     [ 63 154 183 147 221  61  27 217   8 141 124  14 252 110  83   8]
-- PB = 
--     [201  45 134 249   2 189  49 136  52 112  14  76 253 126 247  81]
--     [246 133  36 212 166 156 120 112  13 162 116  70 194  26 132 150]
--     [ 18 207 245 237 214  44 202  56  46  39 106  51  56 196 137  94]
--     [223  48 148  47 114 153 110  74 132 231  87 215 226 136  99  25]
--     [ 95 142  56  80 100   5 130 215  88 255 198  27 190   4 172 207]
--     [ 32 105 199 180   0  61 216  97 218  78 201 121 111  75 249 134]
--     [251  69 112 113  25 223  31 126 222  13   5  76 210  22   3 140]
--     [150  23 184  98  64 199 146  27 116  86 208 204 158 156 185  33]
--     [241 107 129 107 178  85 239 203 182 196 127  31 170  41  11 131]
--     [141   9 117   6 181 119 107 142  86  66  50  18 226 113 175 244]
--     [243 222  46 185   6 182  29  22 239 104 206 115  83 236  71  67]
--     [162 173  16 182 158 124 169  10 144 204 181 170 255  33 153 168]
--     [118  58  37 242 212 252  66  81 228   7 179  79 248 130  86   7]
--     [159  63  96 138 145 153  60  24  86  45 131 120 215 140  51 184]
--     [ 74 112 179 235 183 159 246 245 252 239 140 170  14  56   5  45]
--     [219  35  24 161 242 191  84 189  56 215  48 228 163 125  54 229]

-- OUTPUT:
-- DIFF = 
--     [187  99 120 214 131  98 163   0  35   0 159 131 125  72 135  66]
--     [ 56  23  21  39  59  48  21  18  78  12  43 113  72 158 100  38]
--     [217  31  47 204  52  64   6  53   4  23 138 125   7  42  85  67]
--     [ 91  25 123  55  98 105  47  49  49 148   4 166  30  56  11 211]
--     [  1  69  24 121  29  36  79  37  61   1  52 219  22 147  48 178]
--     [128  36  31 137  16  24 182 114 123 161  10 115  53  33 107  30]
--     [ 68  21  26  54  25  32  45  53 145  97 226  29 208 216 159  59]
--     [ 26 169  62 131 155  47  66 175 118  10 146  17 138  89 174 177]
--     [104  64  53 117  83  67 144  56  70 112 122 115   9  61  67  40]
--     [ 70  48  14  87  84  37  15  21   2 173  33 158 102  33 149  19]
--     [145 159 182   5 218 134 214 125 209   7 114  94 156   5 142  12]
--     [102  47 166 151 138   7  50 120 129  30  18  51 183  50  98 128]
--     [109  32 156  67 111  75   7 119  24 101 146  34 128  21  80  66]
--     [ 70 138  66  90  95  67  47  91 131  27  72  33   4  38  57  66]
--     [ 66   3  87 165 127 128 140 124 231  13  47   8  11  64 100 130]
--     [156 119 159  14  21 130  57  28  48  74  76 214  89  15  29 221]

-- SAD_value = sum(SAD) = 21634 = "0101010010000010"



library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_unsigned.all;
--use ieee.numeric_std.all;


entity tb_SAD is
end entity tb_SAD; -- tb_SAD


architecture struct of tb_SAD is
	
	component SAD is
		generic(
			N          : positive := 8;
			M          : positive := 16
		);
		port(
			CLK        : in  std_logic;
			RST        : in  std_logic;
			EN         : in  std_logic;
			PA         : in  std_logic_vector(N-1  downto 0);
			PB         : in  std_logic_vector(N-1  downto 0);
			
			SAD        : out std_logic_vector(M-1 downto 0); 
			DATA_VALID : out std_logic
		);
	end component SAD;


	constant Nbit    : positive := 8;
	constant Mbit    : positive := 16;
	constant clk_per : time     := 5 ns;

	signal clk       : std_logic := '0';
	signal reset     : std_logic ;
	signal enable    : std_logic ;
	signal PA        : std_logic_vector(Nbit-1 downto 0) := "00000000";
	signal PB        : std_logic_vector(Nbit-1 downto 0) := "XXXXXXXX";
	
	signal testing   : Boolean   := True;




begin
	clk <= not clk after clk_per/2 when testing;-- ELSE '0';


	sad_i: SAD
		generic map(Nbit, Mbit)
		port map(clk, reset, enable, PA, PB, open, open);


	drive_p: process
	  	begin
			
			
			wait for 23 ns;
			reset <= '1';
			enable <= '0';
			wait until rising_edge(clk);
			PB <= "00000000";
			wait for 40 ns;
			reset <= '0';
			wait until rising_edge(clk);
			enable <= '1';
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "11001001";
			wait until rising_edge(clk);

			PA <= "10010000";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "10000110";
			wait until rising_edge(clk);

			PA <= "00100011";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "10000101";
			PB <= "00000010";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "10111101";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "00110001";
			wait until rising_edge(clk);

			PA <= "10001000";
			PB <= "10001000";
			wait until rising_edge(clk);

			PA <= "01010111";
			PB <= "00110100";
			wait until rising_edge(clk);

			PA <= "01110000";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "10101101";
			PB <= "00001110";
			wait until rising_edge(clk);

			PA <= "11001111";
			PB <= "01001100";
			wait until rising_edge(clk);

			PA <= "10000000";
			PB <= "11111101";
			wait until rising_edge(clk);

			PA <= "00110110";
			PB <= "01111110";
			wait until rising_edge(clk);

			PA <= "01110000";
			PB <= "11110111";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "11110110";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "10000101";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "00100100";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "11010100";
			wait until rising_edge(clk);

			PA <= "01101011";
			PB <= "10100110";
			wait until rising_edge(clk);

			PA <= "11001100";
			PB <= "10011100";
			wait until rising_edge(clk);

			PA <= "01100011";
			PB <= "01111000";
			wait until rising_edge(clk);

			PA <= "10000010";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "00001101";
			wait until rising_edge(clk);

			PA <= "10101110";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01110100";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "01000110";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "11000010";
			wait until rising_edge(clk);

			PA <= "10111000";
			PB <= "00011010";
			wait until rising_edge(clk);

			PA <= "00100000";
			PB <= "10000100";
			wait until rising_edge(clk);

			PA <= "10111100";
			PB <= "10010110";
			wait until rising_edge(clk);

			PA <= "11101011";
			PB <= "00010010";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "11001111";
			wait until rising_edge(clk);

			PA <= "11000110";
			PB <= "11110101";
			wait until rising_edge(clk);

			PA <= "00100001";
			PB <= "11101101";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "11010110";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00101100";
			wait until rising_edge(clk);

			PA <= "11010000";
			PB <= "11001010";
			wait until rising_edge(clk);

			PA <= "01101101";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "00101110";
			wait until rising_edge(clk);

			PA <= "00111110";
			PB <= "00100111";
			wait until rising_edge(clk);

			PA <= "11110100";
			PB <= "01101010";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "00110011";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "11000100";
			wait until rising_edge(clk);

			PA <= "11011110";
			PB <= "10001001";
			wait until rising_edge(clk);

			PA <= "00011011";
			PB <= "01011110";
			wait until rising_edge(clk);

			PA <= "10000100";
			PB <= "11011111";
			wait until rising_edge(clk);

			PA <= "00010111";
			PB <= "00110000";
			wait until rising_edge(clk);

			PA <= "00011001";
			PB <= "10010100";
			wait until rising_edge(clk);

			PA <= "01100110";
			PB <= "00101111";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "01110010";
			wait until rising_edge(clk);

			PA <= "00110000";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "01101110";
			wait until rising_edge(clk);

			PA <= "00011001";
			PB <= "01001010";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "10000100";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "11100111";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "01010111";
			wait until rising_edge(clk);

			PA <= "00110001";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "11000100";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "10001000";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "01100011";
			wait until rising_edge(clk);

			PA <= "11101100";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "01011110";
			PB <= "01011111";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "10001110";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "01010000";
			wait until rising_edge(clk);

			PA <= "01000111";
			PB <= "01100100";
			wait until rising_edge(clk);

			PA <= "00101001";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "00110011";
			PB <= "10000010";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "10010101";
			PB <= "01011000";
			wait until rising_edge(clk);

			PA <= "11111110";
			PB <= "11111111";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "11000110";
			wait until rising_edge(clk);

			PA <= "11110110";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "10111110";
			wait until rising_edge(clk);

			PA <= "10010111";
			PB <= "00000100";
			wait until rising_edge(clk);

			PA <= "11011100";
			PB <= "10101100";
			wait until rising_edge(clk);

			PA <= "00011101";
			PB <= "11001111";
			wait until rising_edge(clk);

			PA <= "10100000";
			PB <= "00100000";
			wait until rising_edge(clk);

			PA <= "10001101";
			PB <= "01101001";
			wait until rising_edge(clk);

			PA <= "11100110";
			PB <= "11000111";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "10110100";
			wait until rising_edge(clk);

			PA <= "00010000";
			PB <= "00000000";
			wait until rising_edge(clk);

			PA <= "00100101";
			PB <= "00111101";
			wait until rising_edge(clk);

			PA <= "00100010";
			PB <= "11011000";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "01100001";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "11011010";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01001110";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "11001001";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "01111001";
			wait until rising_edge(clk);

			PA <= "00111010";
			PB <= "01101111";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "01001011";
			wait until rising_edge(clk);

			PA <= "10001110";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "10100100";
			PB <= "10000110";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "11111011";
			wait until rising_edge(clk);

			PA <= "01011010";
			PB <= "01000101";
			wait until rising_edge(clk);

			PA <= "10001010";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "00111011";
			PB <= "01110001";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "11111111";
			PB <= "11011111";
			wait until rising_edge(clk);

			PA <= "01001100";
			PB <= "00011111";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01111110";
			wait until rising_edge(clk);

			PA <= "01001101";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "00001101";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "01101001";
			PB <= "01001100";
			wait until rising_edge(clk);

			PA <= "00000010";
			PB <= "11010010";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "00000011";
			wait until rising_edge(clk);

			PA <= "11000111";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "10010110";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "00010111";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "10111000";
			wait until rising_edge(clk);

			PA <= "11100101";
			PB <= "01100010";
			wait until rising_edge(clk);

			PA <= "11011011";
			PB <= "01000000";
			wait until rising_edge(clk);

			PA <= "10011000";
			PB <= "11000111";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "10010010";
			wait until rising_edge(clk);

			PA <= "11001010";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "11101010";
			PB <= "01110100";
			wait until rising_edge(clk);

			PA <= "01001100";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "00111110";
			PB <= "11010000";
			wait until rising_edge(clk);

			PA <= "10111011";
			PB <= "11001100";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "10011110";
			wait until rising_edge(clk);

			PA <= "01000011";
			PB <= "10011100";
			wait until rising_edge(clk);

			PA <= "00001011";
			PB <= "10111001";
			wait until rising_edge(clk);

			PA <= "11010010";
			PB <= "00100001";
			wait until rising_edge(clk);

			PA <= "10001001";
			PB <= "11110001";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01001100";
			PB <= "10000001";
			wait until rising_edge(clk);

			PA <= "11100000";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "10110010";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "01010101";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "11001011";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "01010100";
			PB <= "11000100";
			wait until rising_edge(clk);

			PA <= "11111001";
			PB <= "01111111";
			wait until rising_edge(clk);

			PA <= "10010010";
			PB <= "00011111";
			wait until rising_edge(clk);

			PA <= "10100001";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "01100110";
			PB <= "00101001";
			wait until rising_edge(clk);

			PA <= "01001110";
			PB <= "00001011";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "10001101";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "10000011";
			PB <= "01110101";
			wait until rising_edge(clk);

			PA <= "01011101";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "01100001";
			PB <= "10110101";
			wait until rising_edge(clk);

			PA <= "10011100";
			PB <= "01110111";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "10001110";
			wait until rising_edge(clk);

			PA <= "01010100";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01000010";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00110010";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "00010010";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "01110001";
			wait until rising_edge(clk);

			PA <= "00011010";
			PB <= "10101111";
			wait until rising_edge(clk);

			PA <= "11100001";
			PB <= "11110100";
			wait until rising_edge(clk);

			PA <= "01100010";
			PB <= "11110011";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "11100100";
			PB <= "00101110";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "10111001";
			wait until rising_edge(clk);

			PA <= "11100000";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "00110000";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "11110011";
			PB <= "00011101";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "00011110";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "01101111";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "11001110";
			wait until rising_edge(clk);

			PA <= "11010001";
			PB <= "01110011";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01010011";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "11101100";
			wait until rising_edge(clk);

			PA <= "11010101";
			PB <= "01000111";
			wait until rising_edge(clk);

			PA <= "01001111";
			PB <= "01000011";
			wait until rising_edge(clk);

			PA <= "00111100";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "01111110";
			PB <= "10101101";
			wait until rising_edge(clk);

			PA <= "10110110";
			PB <= "00010000";
			wait until rising_edge(clk);

			PA <= "00011111";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "10011110";
			wait until rising_edge(clk);

			PA <= "10000011";
			PB <= "01111100";
			wait until rising_edge(clk);

			PA <= "01110111";
			PB <= "10101001";
			wait until rising_edge(clk);

			PA <= "10000010";
			PB <= "00001010";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "10010000";
			wait until rising_edge(clk);

			PA <= "10101110";
			PB <= "11001100";
			wait until rising_edge(clk);

			PA <= "10100011";
			PB <= "10110101";
			wait until rising_edge(clk);

			PA <= "11011101";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "01001000";
			PB <= "11111111";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00100001";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "00101000";
			PB <= "10101000";
			wait until rising_edge(clk);

			PA <= "11100011";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "01011010";
			PB <= "00111010";
			wait until rising_edge(clk);

			PA <= "11000001";
			PB <= "00100101";
			wait until rising_edge(clk);

			PA <= "10101111";
			PB <= "11110010";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "11010100";
			wait until rising_edge(clk);

			PA <= "10110001";
			PB <= "11111100";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01000010";
			wait until rising_edge(clk);

			PA <= "11001000";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00000111";
			wait until rising_edge(clk);

			PA <= "00100001";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "00101101";
			PB <= "01001111";
			wait until rising_edge(clk);

			PA <= "01111000";
			PB <= "11111000";
			wait until rising_edge(clk);

			PA <= "10010111";
			PB <= "10000010";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "00000111";
			wait until rising_edge(clk);

			PA <= "11100101";
			PB <= "10011111";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "00111111";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "01100000";
			wait until rising_edge(clk);

			PA <= "11100100";
			PB <= "10001010";
			wait until rising_edge(clk);

			PA <= "11110000";
			PB <= "10010001";
			wait until rising_edge(clk);

			PA <= "01010110";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "01101011";
			PB <= "00111100";
			wait until rising_edge(clk);

			PA <= "01110011";
			PB <= "00011000";
			wait until rising_edge(clk);

			PA <= "11011001";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "11001011";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "10011001";
			PB <= "01111000";
			wait until rising_edge(clk);

			PA <= "11011011";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "01100110";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00110011";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "10111000";
			wait until rising_edge(clk);

			PA <= "10001100";
			PB <= "01001010";
			wait until rising_edge(clk);

			PA <= "01110011";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "01000110";
			PB <= "11101011";
			wait until rising_edge(clk);

			PA <= "00111000";
			PB <= "10110111";
			wait until rising_edge(clk);

			PA <= "00011111";
			PB <= "10011111";
			wait until rising_edge(clk);

			PA <= "01101010";
			PB <= "11110110";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "11110101";
			wait until rising_edge(clk);

			PA <= "00010101";
			PB <= "11111100";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "10111011";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "00000011";
			PB <= "00001110";
			wait until rising_edge(clk);

			PA <= "01111000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "01101001";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "10101111";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "11011011";
			wait until rising_edge(clk);

			PA <= "10011010";
			PB <= "00100011";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "00011000";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "10100001";
			wait until rising_edge(clk);

			PA <= "11011101";
			PB <= "11110010";
			wait until rising_edge(clk);

			PA <= "00111101";
			PB <= "10111111";
			wait until rising_edge(clk);

			PA <= "00011011";
			PB <= "01010100";
			wait until rising_edge(clk);

			PA <= "11011001";
			PB <= "10111101";
			wait until rising_edge(clk);

			PA <= "00001000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "10001101";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "00110000";
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "10100011";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "01111101";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00110110";
			wait until rising_edge(clk);

			PA <= "00001000";
			PB <= "11100101";
			wait until rising_edge(clk);
			----------------------------------------
			wait for 50 ns;
			reset <= '1';
			wait for 72 ns;
			reset <='0';
			----------------------------------------

			PA <= "00001110";
			PB <= "11001001";
			wait until rising_edge(clk);

			PA <= "10010000";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "10000110";
			wait until rising_edge(clk);

			PA <= "00100011";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "10000101";
			PB <= "00000010";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "10111101";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "00110001";
			wait until rising_edge(clk);

			PA <= "10001000";
			PB <= "10001000";
			wait until rising_edge(clk);

			PA <= "01010111";
			PB <= "00110100";
			wait until rising_edge(clk);

			PA <= "01110000";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "10101101";
			PB <= "00001110";
			wait until rising_edge(clk);

			PA <= "11001111";
			PB <= "01001100";
			wait until rising_edge(clk);

			PA <= "10000000";
			PB <= "11111101";
			wait until rising_edge(clk);

			PA <= "00110110";
			PB <= "01111110";
			wait until rising_edge(clk);

			PA <= "01110000";
			PB <= "11110111";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "11110110";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "10000101";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "00100100";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "11010100";
			wait until rising_edge(clk);

			PA <= "01101011";
			PB <= "10100110";
			wait until rising_edge(clk);

			PA <= "11001100";
			PB <= "10011100";
			wait until rising_edge(clk);

			PA <= "01100011";
			PB <= "01111000";
			wait until rising_edge(clk);

			PA <= "10000010";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "00001101";
			wait until rising_edge(clk);

			enable <= '0';
			PA <= "10101110";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01110100";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "01000110";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "11000010";
			wait until rising_edge(clk);

			PA <= "10111000";
			PB <= "00011010";
			wait until rising_edge(clk);

			PA <= "00100000";
			PB <= "10000100";
			wait until rising_edge(clk);

			PA <= "10111100";
			PB <= "10010110";
			wait until rising_edge(clk);

			PA <= "11101011";
			PB <= "00010010";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "11001111";
			wait until rising_edge(clk);

			PA <= "11000110";
			PB <= "11110101";
			wait until rising_edge(clk);

			PA <= "00100001";
			PB <= "11101101";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "11010110";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00101100";
			wait until rising_edge(clk);

			PA <= "11010000";
			PB <= "11001010";
			wait until rising_edge(clk);

			PA <= "01101101";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "00101110";
			wait until rising_edge(clk);

			PA <= "00111110";
			PB <= "00100111";
			wait until rising_edge(clk);

			PA <= "11110100";
			PB <= "01101010";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "00110011";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "11000100";
			wait until rising_edge(clk);

			PA <= "11011110";
			PB <= "10001001";
			wait until rising_edge(clk);

			PA <= "00011011";
			PB <= "01011110";
			wait until rising_edge(clk);

			PA <= "10000100";
			PB <= "11011111";
			wait until rising_edge(clk);

			PA <= "00010111";
			PB <= "00110000";
			wait until rising_edge(clk);

			PA <= "00011001";
			PB <= "10010100";
			wait until rising_edge(clk);

			enable <= '1';
			PA <= "01100110";
			PB <= "00101111";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "01110010";
			wait until rising_edge(clk);

			PA <= "00110000";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "01101110";
			wait until rising_edge(clk);

			PA <= "00011001";
			PB <= "01001010";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "10000100";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "11100111";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "01010111";
			wait until rising_edge(clk);

			PA <= "00110001";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "11000100";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "10001000";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "01100011";
			wait until rising_edge(clk);

			PA <= "11101100";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "01011110";
			PB <= "01011111";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "10001110";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "01010000";
			wait until rising_edge(clk);

			PA <= "01000111";
			PB <= "01100100";
			wait until rising_edge(clk);

			PA <= "00101001";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "00110011";
			PB <= "10000010";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "10010101";
			PB <= "01011000";
			wait until rising_edge(clk);

			PA <= "11111110";
			PB <= "11111111";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "11000110";
			wait until rising_edge(clk);

			PA <= "11110110";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "11010100";
			PB <= "10111110";
			wait until rising_edge(clk);

			PA <= "10010111";
			PB <= "00000100";
			wait until rising_edge(clk);

			PA <= "11011100";
			PB <= "10101100";
			wait until rising_edge(clk);

			PA <= "00011101";
			PB <= "11001111";
			wait until rising_edge(clk);

			PA <= "10100000";
			PB <= "00100000";
			wait until rising_edge(clk);

			PA <= "10001101";
			PB <= "01101001";
			wait until rising_edge(clk);

			PA <= "11100110";
			PB <= "11000111";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "10110100";
			wait until rising_edge(clk);

			PA <= "00010000";
			PB <= "00000000";
			wait until rising_edge(clk);

			PA <= "00100101";
			PB <= "00111101";
			wait until rising_edge(clk);

			PA <= "00100010";
			PB <= "11011000";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "01100001";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "11011010";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01001110";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "11001001";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "01111001";
			wait until rising_edge(clk);

			PA <= "00111010";
			PB <= "01101111";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "01001011";
			wait until rising_edge(clk);

			PA <= "10001110";
			PB <= "11111001";
			wait until rising_edge(clk);

			PA <= "10100100";
			PB <= "10000110";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "11111011";
			wait until rising_edge(clk);

			PA <= "01011010";
			PB <= "01000101";
			wait until rising_edge(clk);

			PA <= "10001010";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "00111011";
			PB <= "01110001";
			wait until rising_edge(clk);

			PA <= "00110010";
			PB <= "00011001";
			wait until rising_edge(clk);

			PA <= "11111111";
			PB <= "11011111";
			wait until rising_edge(clk);

			reset <= '1';
			PA <= "01001100";
			PB <= "00011111";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01111110";
			wait until rising_edge(clk);

			PA <= "01001101";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "00001101";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "00000101";
			wait until rising_edge(clk);

			reset <= '0';
			PA <= "01101001";
			PB <= "01001100";
			wait until rising_edge(clk);

			PA <= "00000010";
			PB <= "11010010";
			wait until rising_edge(clk);

			PA <= "11101110";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "00000011";
			wait until rising_edge(clk);

			PA <= "11000111";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "10010110";
			wait until rising_edge(clk);

			PA <= "11000000";
			PB <= "00010111";
			wait until rising_edge(clk);

			PA <= "01111010";
			PB <= "10111000";
			wait until rising_edge(clk);

			PA <= "11100101";
			PB <= "01100010";
			wait until rising_edge(clk);

			PA <= "11011011";
			PB <= "01000000";
			wait until rising_edge(clk);

			PA <= "10011000";
			PB <= "11000111";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "10010010";
			wait until rising_edge(clk);

			PA <= "11001010";
			PB <= "00011011";
			wait until rising_edge(clk);

			PA <= "11101010";
			PB <= "01110100";
			wait until rising_edge(clk);

			PA <= "01001100";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "00111110";
			PB <= "11010000";
			wait until rising_edge(clk);

			PA <= "10111011";
			PB <= "11001100";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "10011110";
			wait until rising_edge(clk);

			PA <= "01000011";
			PB <= "10011100";
			wait until rising_edge(clk);

			PA <= "00001011";
			PB <= "10111001";
			wait until rising_edge(clk);

			PA <= "11010010";
			PB <= "00100001";
			wait until rising_edge(clk);

			PA <= "10001001";
			PB <= "11110001";
			wait until rising_edge(clk);

			PA <= "00101011";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01001100";
			PB <= "10000001";
			wait until rising_edge(clk);

			PA <= "11100000";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "10110010";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "01010101";
			wait until rising_edge(clk);

			PA <= "01011111";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "11001011";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "01010100";
			PB <= "11000100";
			wait until rising_edge(clk);

			PA <= "11111001";
			PB <= "01111111";
			wait until rising_edge(clk);

			PA <= "10010010";
			PB <= "00011111";
			wait until rising_edge(clk);

			PA <= "10100001";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "01100110";
			PB <= "00101001";
			wait until rising_edge(clk);

			PA <= "01001110";
			PB <= "00001011";
			wait until rising_edge(clk);

			PA <= "01011011";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "11010011";
			PB <= "10001101";
			wait until rising_edge(clk);

			PA <= "00111001";
			PB <= "00001001";
			wait until rising_edge(clk);

			PA <= "10000011";
			PB <= "01110101";
			wait until rising_edge(clk);

			PA <= "01011101";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "01100001";
			PB <= "10110101";
			wait until rising_edge(clk);

			PA <= "10011100";
			PB <= "01110111";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "01101011";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "10001110";
			wait until rising_edge(clk);

			PA <= "01010100";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01000010";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00110010";
			wait until rising_edge(clk);

			PA <= "10110000";
			PB <= "00010010";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "11100010";
			wait until rising_edge(clk);

			PA <= "01010000";
			PB <= "01110001";
			wait until rising_edge(clk);

			PA <= "00011010";
			PB <= "10101111";
			wait until rising_edge(clk);

			PA <= "11100001";
			PB <= "11110100";
			wait until rising_edge(clk);

			PA <= "01100010";
			PB <= "11110011";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "11011110";
			wait until rising_edge(clk);

			PA <= "11100100";
			PB <= "00101110";
			wait until rising_edge(clk);

			PA <= "10111110";
			PB <= "10111001";
			wait until rising_edge(clk);

			PA <= "11100000";
			PB <= "00000110";
			wait until rising_edge(clk);

			PA <= "00110000";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "11110011";
			PB <= "00011101";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "00010110";
			wait until rising_edge(clk);

			PA <= "00011110";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "01101111";
			PB <= "01101000";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "11001110";
			wait until rising_edge(clk);

			PA <= "11010001";
			PB <= "01110011";
			wait until rising_edge(clk);

			PA <= "11101111";
			PB <= "01010011";
			wait until rising_edge(clk);

			PA <= "11100111";
			PB <= "11101100";
			wait until rising_edge(clk);

			PA <= "11010101";
			PB <= "01000111";
			wait until rising_edge(clk);

			PA <= "01001111";
			PB <= "01000011";
			wait until rising_edge(clk);

			PA <= "00111100";
			PB <= "10100010";
			wait until rising_edge(clk);

			PA <= "01111110";
			PB <= "10101101";
			wait until rising_edge(clk);

			PA <= "10110110";
			PB <= "00010000";
			wait until rising_edge(clk);

			PA <= "00011111";
			PB <= "10110110";
			wait until rising_edge(clk);

			PA <= "00010100";
			PB <= "10011110";
			wait until rising_edge(clk);

			PA <= "10000011";
			PB <= "01111100";
			wait until rising_edge(clk);

			PA <= "01110111";
			PB <= "10101001";
			wait until rising_edge(clk);

			PA <= "10000010";
			PB <= "00001010";
			wait until rising_edge(clk);

			PA <= "00001111";
			PB <= "10010000";
			wait until rising_edge(clk);

			PA <= "10101110";
			PB <= "11001100";
			wait until rising_edge(clk);

			PA <= "10100011";
			PB <= "10110101";
			wait until rising_edge(clk);

			PA <= "11011101";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "01001000";
			PB <= "11111111";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00100001";
			wait until rising_edge(clk);

			PA <= "11111011";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "00101000";
			PB <= "10101000";
			wait until rising_edge(clk);

			PA <= "11100011";
			PB <= "01110110";
			wait until rising_edge(clk);

			PA <= "01011010";
			PB <= "00111010";
			wait until rising_edge(clk);

			PA <= "11000001";
			PB <= "00100101";
			wait until rising_edge(clk);

			PA <= "10101111";
			PB <= "11110010";
			wait until rising_edge(clk);

			PA <= "01100101";
			PB <= "11010100";
			wait until rising_edge(clk);

			PA <= "10110001";
			PB <= "11111100";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "01000010";
			wait until rising_edge(clk);

			PA <= "11001000";
			PB <= "01010001";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00000111";
			wait until rising_edge(clk);

			PA <= "00100001";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "00101101";
			PB <= "01001111";
			wait until rising_edge(clk);

			PA <= "01111000";
			PB <= "11111000";
			wait until rising_edge(clk);

			PA <= "10010111";
			PB <= "10000010";
			wait until rising_edge(clk);

			PA <= "00000110";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "01001001";
			PB <= "00000111";
			wait until rising_edge(clk);

			PA <= "11100101";
			PB <= "10011111";
			wait until rising_edge(clk);

			PA <= "11001001";
			PB <= "00111111";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "01100000";
			wait until rising_edge(clk);

			PA <= "11100100";
			PB <= "10001010";
			wait until rising_edge(clk);

			PA <= "11110000";
			PB <= "10010001";
			wait until rising_edge(clk);

			PA <= "01010110";
			PB <= "10011001";
			wait until rising_edge(clk);

			PA <= "01101011";
			PB <= "00111100";
			wait until rising_edge(clk);

			PA <= "01110011";
			PB <= "00011000";
			wait until rising_edge(clk);

			PA <= "11011001";
			PB <= "01010110";
			wait until rising_edge(clk);

			PA <= "00010010";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "11001011";
			PB <= "10000011";
			wait until rising_edge(clk);

			PA <= "10011001";
			PB <= "01111000";
			wait until rising_edge(clk);

			PA <= "11011011";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "01100110";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "01101100";
			PB <= "00110011";
			wait until rising_edge(clk);

			PA <= "11111010";
			PB <= "10111000";
			wait until rising_edge(clk);

			PA <= "10001100";
			PB <= "01001010";
			wait until rising_edge(clk);

			PA <= "01110011";
			PB <= "01110000";
			wait until rising_edge(clk);

			PA <= "01011100";
			PB <= "10110011";
			wait until rising_edge(clk);

			PA <= "01000110";
			PB <= "11101011";
			wait until rising_edge(clk);

			PA <= "00111000";
			PB <= "10110111";
			wait until rising_edge(clk);

			PA <= "00011111";
			PB <= "10011111";
			wait until rising_edge(clk);

			PA <= "01101010";
			PB <= "11110110";
			wait until rising_edge(clk);

			PA <= "01111001";
			PB <= "11110101";
			wait until rising_edge(clk);

			PA <= "00010101";
			PB <= "11111100";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "11101111";
			wait until rising_edge(clk);

			PA <= "10111011";
			PB <= "10001100";
			wait until rising_edge(clk);

			PA <= "10100010";
			PB <= "10101010";
			wait until rising_edge(clk);

			PA <= "00000011";
			PB <= "00001110";
			wait until rising_edge(clk);

			PA <= "01111000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "01101001";
			PB <= "00000101";
			wait until rising_edge(clk);

			PA <= "10101111";
			PB <= "00101101";
			wait until rising_edge(clk);

			PA <= "00111111";
			PB <= "11011011";
			wait until rising_edge(clk);

			PA <= "10011010";
			PB <= "00100011";
			wait until rising_edge(clk);

			PA <= "10110111";
			PB <= "00011000";
			wait until rising_edge(clk);

			PA <= "10010011";
			PB <= "10100001";
			wait until rising_edge(clk);

			PA <= "11011101";
			PB <= "11110010";
			wait until rising_edge(clk);

			PA <= "00111101";
			PB <= "10111111";
			wait until rising_edge(clk);

			PA <= "00011011";
			PB <= "01010100";
			wait until rising_edge(clk);

			PA <= "11011001";
			PB <= "10111101";
			wait until rising_edge(clk);

			PA <= "00001000";
			PB <= "00111000";
			wait until rising_edge(clk);

			PA <= "10001101";
			PB <= "11010111";
			wait until rising_edge(clk);

			PA <= "01111100";
			PB <= "00110000";
			wait until rising_edge(clk);

			PA <= "00001110";
			PB <= "11100100";
			wait until rising_edge(clk);

			PA <= "11111100";
			PB <= "10100011";
			wait until rising_edge(clk);

			PA <= "01101110";
			PB <= "01111101";
			wait until rising_edge(clk);

			PA <= "01010011";
			PB <= "00110110";
			wait until rising_edge(clk);

			PA <= "00001000";
			PB <= "11100101";
			wait until rising_edge(clk);

			----------------------------------


	  		wait for 190 ns;
	  		testing <= False;
	  		wait;
	  	end process;

	  	--drive_rst: process
	  	--begin
	  	--	wait for 80 ns;
	    --	reset <= '1';
	  	--	wait for 40 ns;
	  	--	reset <= '0';
	  	--	wait until rising_edge(clk);
	  	--	wait;
	  	--end process;


	  	--drive_en : process
	  	--begin
  		--	wait for 44 ns;
	  	--	enable <= '1';
	  	--	wait for 89 ns;
	  	--	enable <= '0';
	  	--	wait for 71 ns;
		--	enable <= '1';
	  	--	wait for 1111 ns;
	  	--	wait;
	  	--end process;

end architecture;

