---------------------------------------------
-- Title       : tb_SAD
-- Project     : Final project: SAD Calculation
---------------------------------------------
-- File        : tb_SAD.vhd
-- Language    : VHDL
-- Author(s)   : Francesco Urbani
-- Company     : 
-- Created     : Fri Jun  1 09:33:11 CEST 2018
---------------------------------------------
-- Description : Autogenerated test bench for SAD.vhd
---------------------------------------------
-- Update      :
---------------------------------------------

-- THIS TEST BENCH IS AUTOGENERATED FROM SAD_model.py
-- WARNING! All changes made in this file might be lost!



-- INPUTS:
-- N  = 10 bits
-- px = 11

-- SAD_bits_min := min num bits to correctly represent SAD
-- SAD_bits_min = ceil( log2( (2**N-1) * px**2 )) = 
--              = ceil( log2( 1023 * 121 )) = 
--              = 17


-- PA = 
--     [ 334   55   94  193  100  456  724 1002  586  659  983]
--     [ 405  958  205  470  936  887  724 1013  880  295   54]
--     [809 897 813 624 159 893 279 439 686 529 552]
--     [756 588  43 415 885  32 293 187 936 969 783]
--     [636 261 993 835 360 851 929 568 111  89 473]
--     [138 588 255 678 393 153 261  11 106 126 793]
--     [500  73  76 268 706 797 382 286 223 398 863]
--     [966 132 351 990 643 499 840 324 818 176 949]
--     [953 350  14 296 275 912 532 184 334 103 318]
--     [ 103  844  220  206  421  887  118  434   83 1003  890]
--     [269 285 656   2 710  55 121 963 946 298 952]
-- PB = 
--     [571 986 349 808  60 326 327 731 327 211 700]
--     [289 757  82 464 734 941 360 143 707 911   8]
--     [559 187 690 693 594 252 763 879 174 989 782]
--     [ 23 966 794 210 852 780 437  95 526 116 902]
--     [295 747 277 302 816 859 344 812 532  28 828]
--     [248 667 721 546 476 326 718 552 953 953 190]
--     [514 176 173  68  69  68 884 765 611 683 315]
--     [982 160 757  83 736 771 602 407 295 974 929]
--     [645 407 829 907 660 268 636  92 672 455 308]
--     [492 666 437  58 478 336 437 656 952 710 897]
--     [ 458  804  341   11 1018  995  362   46  784  828  253]

-- OUTPUT:
-- DIFF = 
--     [237 931 255 615  40 130 397 271 259 448 283]
--     [116 201 123   6 202  54 364 870 173 616  46]
--     [250 710 123  69 435 641 484 440 512 460 230]
--     [733 378 751 205  33 748 144  92 410 853 119]
--     [341 486 716 533 456   8 585 244 421  61 355]
--     [110  79 466 132  83 173 457 541 847 827 603]
--     [ 14 103  97 200 637 729 502 479 388 285 548]
--     [ 16  28 406 907  93 272 238  83 523 798  20]
--     [308  57 815 611 385 644 104  92 338 352  10]
--     [389 178 217 148  57 551 319 222 869 293   7]
--     [189 519 315   9 308 940 241 917 162 530 699]

-- SAD_value = sum(SAD) = 43142 = "01010100010000110"



library ieee;
use ieee.std_logic_1164.all;
--use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;


entity tb_SAD is
end entity tb_SAD; -- tb_SAD


architecture struct of tb_SAD is
	
	component SAD is
		generic(
			Npixel     : positive ;      -- total # of pixels of the image
			
			Nbit       : positive ;        -- # of bits needed to represent the value of each pixel
			SAD_bits   : positive  	-- # of bits needed to represent the output
		);
		port(
			CLK        : in  std_logic;
			RST        : in  std_logic;
			EN         : in  std_logic;
			PA         : in  std_logic_vector(Nbit-1  downto 0);
			PB         : in  std_logic_vector(Nbit-1  downto 0);
			
			SAD        : out std_logic_vector(SAD_bits-1 downto 0); 
			DATA_VALID : out std_logic
		);
	end component SAD;


	constant Npixel  : positive := 121;
	constant Nbit    : positive := 10;
	constant Mbit    : positive := 17;
	constant clk_per : time     := 5 ns;

	signal clk       : std_logic := '0';
	signal reset     : std_logic ;
	signal enable    : std_logic ;
	signal PA        : std_logic_vector(Nbit-1 downto 0) := "0000000000";
	signal PB        : std_logic_vector(Nbit-1 downto 0) := "XXXXXXXXXX";
	
	signal testing   : Boolean   := True;




begin
	clk <= not clk after clk_per/2 when testing;-- ELSE '0';


	sad_i: SAD
		generic map(Npixel, Nbit, Mbit)
		port map(clk, reset, enable, PA, PB, open, open);


	drive_p: process
	  	begin
			
			
			PA <= "0011111101";
			PB <= "0110111111";
			wait until rising_edge(clk);

			PA <= "0010101001";
			PB <= "0010011111";
			wait until rising_edge(clk);

			PA <= "1011111010";
			PB <= "1111000011";
			wait until rising_edge(clk);

			PA <= "1001110010";
			PB <= "1111111100";
			wait until rising_edge(clk);

			PA <= "0001001101";
			PB <= "1111100011";
			wait until rising_edge(clk);

			PA <= "0011111011";
			PB <= "1000100010";
			wait until rising_edge(clk);

			PA <= "1101100111";
			PB <= "0010011001";
			wait until rising_edge(clk);

			PA <= "1011100111";
			PB <= "1011100010";
			wait until rising_edge(clk);

			PA <= "0110101101";
			PB <= "1000111000";
			wait until rising_edge(clk);

			PA <= "1000010111";
			PB <= "0000011001";
			wait until rising_edge(clk);

			PA <= "0000000000";
			PB <= "0000000000";
			wait until rising_edge(clk);

-----------------------


			PA <= "0101001110";
			PB <= "1000111011";
			wait until rising_edge(clk);

			PA <= "0000110111";
			PB <= "1111011010";
			wait until rising_edge(clk);

			PA <= "0001011110";
			PB <= "0101011101";
			wait until rising_edge(clk);

			PA <= "0011000001";
			PB <= "1100101000";
			wait until rising_edge(clk);

			PA <= "0001100100";
			PB <= "0000111100";
			wait until rising_edge(clk);

			PA <= "0111001000";
			PB <= "0101000110";
			wait until rising_edge(clk);

			PA <= "1011010100";
			PB <= "0101000111";
			wait until rising_edge(clk);

			PA <= "1111101010";
			PB <= "1011011011";
			wait until rising_edge(clk);

			PA <= "1001001010";
			PB <= "0101000111";
			wait until rising_edge(clk);

			PA <= "1010010011";
			PB <= "0011010011";
			wait until rising_edge(clk);

			PA <= "1111010111";
			PB <= "1010111100";
			wait until rising_edge(clk);

			PA <= "0110010101";
			PB <= "0100100001";
			wait until rising_edge(clk);

			PA <= "1110111110";
			PB <= "1011110101";
			wait until rising_edge(clk);

			PA <= "0011001101";
			PB <= "0001010010";
			wait until rising_edge(clk);

			PA <= "0111010110";
			PB <= "0111010000";
			wait until rising_edge(clk);

			PA <= "1110101000";
			PB <= "1011011110";
			wait until rising_edge(clk);

			PA <= "1101110111";
			PB <= "1110101101";
			wait until rising_edge(clk);

			PA <= "1011010100";
			PB <= "0101101000";
			wait until rising_edge(clk);

			PA <= "1111110101";
			PB <= "0010001111";
			wait until rising_edge(clk);

			PA <= "1101110000";
			PB <= "1011000011";
			wait until rising_edge(clk);

			PA <= "0100100111";
			PB <= "1110001111";
			wait until rising_edge(clk);

			PA <= "0000110110";
			PB <= "0000001000";
			wait until rising_edge(clk);

			PA <= "1100101001";
			PB <= "1000101111";
			wait until rising_edge(clk);

			PA <= "1110000001";
			PB <= "0010111011";
			wait until rising_edge(clk);

			PA <= "1100101101";
			PB <= "1010110010";
			wait until rising_edge(clk);

			PA <= "1001110000";
			PB <= "1010110101";
			wait until rising_edge(clk);

			PA <= "0010011111";
			PB <= "1001010010";
			wait until rising_edge(clk);

			PA <= "1101111101";
			PB <= "0011111100";
			wait until rising_edge(clk);

			PA <= "0100010111";
			PB <= "1011111011";
			wait until rising_edge(clk);

			PA <= "0110110111";
			PB <= "1101101111";
			wait until rising_edge(clk);

			PA <= "1010101110";
			PB <= "0010101110";
			wait until rising_edge(clk);

			PA <= "1000010001";
			PB <= "1111011101";
			wait until rising_edge(clk);

			PA <= "1000101000";
			PB <= "1100001110";
			wait until rising_edge(clk);

			PA <= "1011110100";
			PB <= "0000010111";
			wait until rising_edge(clk);

			PA <= "1001001100";
			PB <= "1111000110";
			wait until rising_edge(clk);

			PA <= "0000101011";
			PB <= "1100011010";
			wait until rising_edge(clk);

			PA <= "0110011111";
			PB <= "0011010010";
			wait until rising_edge(clk);

			PA <= "1101110101";
			PB <= "1101010100";
			wait until rising_edge(clk);

			PA <= "0000100000";
			PB <= "1100001100";
			wait until rising_edge(clk);

			PA <= "0100100101";
			PB <= "0110110101";
			wait until rising_edge(clk);

			PA <= "0010111011";
			PB <= "0001011111";
			wait until rising_edge(clk);

			PA <= "1110101000";
			PB <= "1000001110";
			wait until rising_edge(clk);

			PA <= "1111001001";
			PB <= "0001110100";
			wait until rising_edge(clk);

			PA <= "1100001111";
			PB <= "1110000110";
			wait until rising_edge(clk);

			PA <= "1001111100";
			PB <= "0100100111";
			wait until rising_edge(clk);

			PA <= "0100000101";
			PB <= "1011101011";
			wait until rising_edge(clk);

			PA <= "1111100001";
			PB <= "0100010101";
			wait until rising_edge(clk);

			PA <= "1101000011";
			PB <= "0100101110";
			wait until rising_edge(clk);

			PA <= "0101101000";
			PB <= "1100110000";
			wait until rising_edge(clk);

			PA <= "1101010011";
			PB <= "1101011011";
			wait until rising_edge(clk);

			PA <= "1110100001";
			PB <= "0101011000";
			wait until rising_edge(clk);

			PA <= "1000111000";
			PB <= "1100101100";
			wait until rising_edge(clk);

			PA <= "0001101111";
			PB <= "1000010100";
			wait until rising_edge(clk);

			PA <= "0001011001";
			PB <= "0000011100";
			wait until rising_edge(clk);

			PA <= "0111011001";
			PB <= "1100111100";
			wait until rising_edge(clk);

			PA <= "0010001010";
			PB <= "0011111000";
			wait until rising_edge(clk);

			PA <= "1001001100";
			PB <= "1010011011";
			wait until rising_edge(clk);

			PA <= "0011111111";
			PB <= "1011010001";
			wait until rising_edge(clk);

			PA <= "1010100110";
			PB <= "1000100010";
			wait until rising_edge(clk);

			PA <= "0110001001";
			PB <= "0111011100";
			wait until rising_edge(clk);

			PA <= "0010011001";
			PB <= "0101000110";
			wait until rising_edge(clk);

			PA <= "0100000101";
			PB <= "1011001110";
			wait until rising_edge(clk);

			PA <= "0000001011";
			PB <= "1000101000";
			wait until rising_edge(clk);

			PA <= "0001101010";
			PB <= "1110111001";
			wait until rising_edge(clk);

			PA <= "0001111110";
			PB <= "1110111001";
			wait until rising_edge(clk);

			PA <= "1100011001";
			PB <= "0010111110";
			wait until rising_edge(clk);

			PA <= "0111110100";
			PB <= "1000000010";
			wait until rising_edge(clk);

			PA <= "0001001001";
			PB <= "0010110000";
			wait until rising_edge(clk);

			PA <= "0001001100";
			PB <= "0010101101";
			wait until rising_edge(clk);

			PA <= "0100001100";
			PB <= "0001000100";
			wait until rising_edge(clk);

			PA <= "1011000010";
			PB <= "0001000101";
			wait until rising_edge(clk);

			PA <= "1100011101";
			PB <= "0001000100";
			wait until rising_edge(clk);

			PA <= "0101111110";
			PB <= "1101110100";
			wait until rising_edge(clk);

			PA <= "0100011110";
			PB <= "1011111101";
			wait until rising_edge(clk);

			PA <= "0011011111";
			PB <= "1001100011";
			wait until rising_edge(clk);

			PA <= "0110001110";
			PB <= "1010101011";
			wait until rising_edge(clk);

			PA <= "1101011111";
			PB <= "0100111011";
			wait until rising_edge(clk);

			PA <= "1111000110";
			PB <= "1111010110";
			wait until rising_edge(clk);

			PA <= "0010000100";
			PB <= "0010100000";
			wait until rising_edge(clk);

			PA <= "0101011111";
			PB <= "1011110101";
			wait until rising_edge(clk);

			PA <= "1111011110";
			PB <= "0001010011";
			wait until rising_edge(clk);

			PA <= "1010000011";
			PB <= "1011100000";
			wait until rising_edge(clk);

			PA <= "0111110011";
			PB <= "1100000011";
			wait until rising_edge(clk);

			PA <= "1101001000";
			PB <= "1001011010";
			wait until rising_edge(clk);

			PA <= "0101000100";
			PB <= "0110010111";
			wait until rising_edge(clk);

			PA <= "1100110010";
			PB <= "0100100111";
			wait until rising_edge(clk);

			PA <= "0010110000";
			PB <= "1111001110";
			wait until rising_edge(clk);

			PA <= "1110110101";
			PB <= "1110100001";
			wait until rising_edge(clk);

			PA <= "1110111001";
			PB <= "1010000101";
			wait until rising_edge(clk);

			PA <= "0101011110";
			PB <= "0110010111";
			wait until rising_edge(clk);

			PA <= "0000001110";
			PB <= "1100111101";
			wait until rising_edge(clk);

			PA <= "0100101000";
			PB <= "1110001011";
			wait until rising_edge(clk);

			PA <= "0100010011";
			PB <= "1010010100";
			wait until rising_edge(clk);

			PA <= "1110010000";
			PB <= "0100001100";
			wait until rising_edge(clk);

			PA <= "1000010100";
			PB <= "1001111100";
			wait until rising_edge(clk);

			PA <= "0010111000";
			PB <= "0001011100";
			wait until rising_edge(clk);

			PA <= "0101001110";
			PB <= "1010100000";
			wait until rising_edge(clk);

			PA <= "0001100111";
			PB <= "0111000111";
			wait until rising_edge(clk);

			PA <= "0100111110";
			PB <= "0100110100";
			wait until rising_edge(clk);

			PA <= "0001100111";
			PB <= "0111101100";
			wait until rising_edge(clk);

			PA <= "1101001100";
			PB <= "1010011010";
			wait until rising_edge(clk);

			PA <= "0011011100";
			PB <= "0110110101";
			wait until rising_edge(clk);

			PA <= "0011001110";
			PB <= "0000111010";
			wait until rising_edge(clk);

			PA <= "0110100101";
			PB <= "0111011110";
			wait until rising_edge(clk);

			PA <= "1101110111";
			PB <= "0101010000";
			wait until rising_edge(clk);

			PA <= "0001110110";
			PB <= "0110110101";
			wait until rising_edge(clk);

			PA <= "0110110010";
			PB <= "1010010000";
			wait until rising_edge(clk);

			PA <= "0001010011";
			PB <= "1110111000";
			wait until rising_edge(clk);

			PA <= "1111101011";
			PB <= "1011000110";
			wait until rising_edge(clk);

			PA <= "1101111010";
			PB <= "1110000001";
			wait until rising_edge(clk);

			PA <= "0100001101";
			PB <= "0111001010";
			wait until rising_edge(clk);

			PA <= "0100011101";
			PB <= "1100100100";
			wait until rising_edge(clk);

			PA <= "1010010000";
			PB <= "0101010101";
			wait until rising_edge(clk);

			PA <= "0000000010";
			PB <= "0000001011";
			wait until rising_edge(clk);

			PA <= "1011000110";
			PB <= "1111111010";
			wait until rising_edge(clk);

			PA <= "0000110111";
			PB <= "1111100011";
			wait until rising_edge(clk);

			PA <= "0001111001";
			PB <= "0101101010";
			wait until rising_edge(clk);

			PA <= "1111000011";
			PB <= "0000101110";
			wait until rising_edge(clk);

			PA <= "1110110010";
			PB <= "1100010000";
			wait until rising_edge(clk);

			PA <= "0100101010";
			PB <= "1100111100";
			wait until rising_edge(clk);

			PA <= "1110111000";
			PB <= "0011111101";
			wait until rising_edge(clk);


------------------------------------------


			PA <= "0000000010";
			PB <= "1011001101";
			wait until rising_edge(clk);

			PA <= "0011111000";
			PB <= "0101011101";
			wait until rising_edge(clk);

			PA <= "0000100101";
			PB <= "1010011111";
			wait until rising_edge(clk);

			PA <= "1011101101";
			PB <= "1101011001";
			wait until rising_edge(clk);

			PA <= "1110101101";
			PB <= "0111010100";
			wait until rising_edge(clk);

			PA <= "0011110000";
			PB <= "0011001101";
			wait until rising_edge(clk);

			PA <= "0000001110";
			PB <= "1111010010";
			wait until rising_edge(clk);

			PA <= "0111001000";
			PB <= "0100011100";
			wait until rising_edge(clk);

			PA <= "1010000100";
			PB <= "0001000001";
			wait until rising_edge(clk);

			PA <= "1010100010";
			PB <= "1000111001";
			wait until rising_edge(clk);

			PA <= "1001100111";
			PB <= "0100111111";
			wait until rising_edge(clk);

			PA <= "1001111000";
			PB <= "0111011001";
			wait until rising_edge(clk);

			PA <= "0101110010";
			PB <= "1111010011";
			wait until rising_edge(clk);

			PA <= "1100111111";
			PB <= "1010000101";
			wait until rising_edge(clk);

			PA <= "1100000011";
			PB <= "0111000111";
			wait until rising_edge(clk);

			PA <= "1111100001";
			PB <= "0011101001";
			wait until rising_edge(clk);

			PA <= "0010011110";
			PB <= "1000101000";
			wait until rising_edge(clk);

			PA <= "0100111100";
			PB <= "0110001001";
			wait until rising_edge(clk);

			PA <= "0010010101";
			PB <= "0001001101";
			wait until rising_edge(clk);

			PA <= "0001101100";
			PB <= "1110100100";
			wait until rising_edge(clk);

			PA <= "0100101110";
			PB <= "1000001000";
			wait until rising_edge(clk);

			PA <= "1011110110";
			PB <= "1101110110";
			wait until rising_edge(clk);

			PA <= "1000101011";
			PB <= "1001111000";
			wait until rising_edge(clk);

			PA <= "0010110011";
			PB <= "0010101011";
			wait until rising_edge(clk);

			PA <= "1111111001";
			PB <= "1100111000";
			wait until rising_edge(clk);

			PA <= "1101010011";
			PB <= "0110101110";
			wait until rising_edge(clk);

			PA <= "1001001111";
			PB <= "1101000110";
			wait until rising_edge(clk);

			PA <= "1110110101";
			PB <= "1101000110";
			wait until rising_edge(clk);

			PA <= "0110101001";
			PB <= "1101011011";
			wait until rising_edge(clk);

			PA <= "1100010111";
			PB <= "0110111010";
			wait until rising_edge(clk);

			PA <= "0010010110";
			PB <= "0000001010";
			wait until rising_edge(clk);

			PA <= "1010101100";
			PB <= "1111110001";
			wait until rising_edge(clk);

			PA <= "0100001111";
			PB <= "0101001101";
			wait until rising_edge(clk);

			PA <= "1111111111";
			PB <= "1011110000";
			wait until rising_edge(clk);

			PA <= "1001010101";
			PB <= "0111110010";
			wait until rising_edge(clk);

			PA <= "0011010010";
			PB <= "1100011010";
			wait until rising_edge(clk);

			PA <= "1010011100";
			PB <= "1100101101";
			wait until rising_edge(clk);

			PA <= "0100011010";
			PB <= "0011011110";
			wait until rising_edge(clk);

			PA <= "0111110110";
			PB <= "0100111100";
			wait until rising_edge(clk);

			PA <= "1001100100";
			PB <= "1110000101";
			wait until rising_edge(clk);

			PA <= "1111010111";
			PB <= "0011100000";
			wait until rising_edge(clk);

			PA <= "0011010010";
			PB <= "0010100001";
			wait until rising_edge(clk);

			PA <= "1011011000";
			PB <= "0100001110";
			wait until rising_edge(clk);

			PA <= "0101010100";
			PB <= "0111010010";
			wait until rising_edge(clk);

			PA <= "0110101101";
			PB <= "0001111101";
			wait until rising_edge(clk);

			PA <= "0001010100";
			PB <= "1110010011";
			wait until rising_edge(clk);

			PA <= "1000111101";
			PB <= "0010000110";
			wait until rising_edge(clk);

			PA <= "1111000010";
			PB <= "0100010100";
			wait until rising_edge(clk);

			PA <= "1100001001";
			PB <= "1011101011";
			wait until rising_edge(clk);

			PA <= "0011110001";
			PB <= "0100111101";
			wait until rising_edge(clk);

			PA <= "1001111001";
			PB <= "0011010010";
			wait until rising_edge(clk);

			PA <= "1011001010";
			PB <= "1100100101";
			wait until rising_edge(clk);

			PA <= "1111100111";
			PB <= "0110111001";
			wait until rising_edge(clk);

			PA <= "0011000000";
			PB <= "1101010000";
			wait until rising_edge(clk);

			PA <= "0100010000";
			PB <= "1100101001";
			wait until rising_edge(clk);

			PA <= "1000110101";
			PB <= "1111000110";
			wait until rising_edge(clk);

			PA <= "1011000100";
			PB <= "0111101101";
			wait until rising_edge(clk);

			PA <= "1100001110";
			PB <= "1110010111";
			wait until rising_edge(clk);

			PA <= "1100010000";
			PB <= "1010011110";
			wait until rising_edge(clk);

			PA <= "1010001111";
			PB <= "1110001011";
			wait until rising_edge(clk);

			PA <= "1001101101";
			PB <= "0011111001";
			wait until rising_edge(clk);

			PA <= "0000001111";
			PB <= "0011101011";
			wait until rising_edge(clk);

			PA <= "1101100101";
			PB <= "0010001010";
			wait until rising_edge(clk);

			PA <= "1100111011";
			PB <= "0001010000";
			wait until rising_edge(clk);

			PA <= "1111110110";
			PB <= "0111101001";
			wait until rising_edge(clk);

			PA <= "1000101101";
			PB <= "0111100100";
			wait until rising_edge(clk);

			PA <= "1111001101";
			PB <= "1111101001";
			wait until rising_edge(clk);

			PA <= "1000101101";
			PB <= "0100010110";
			wait until rising_edge(clk);

			PA <= "1000010011";
			PB <= "1001011101";
			wait until rising_edge(clk);

			PA <= "1110110101";
			PB <= "1001111110";
			wait until rising_edge(clk);

			PA <= "0101010011";
			PB <= "1111000111";
			wait until rising_edge(clk);

			PA <= "1110101010";
			PB <= "0110100010";
			wait until rising_edge(clk);

			PA <= "0010011010";
			PB <= "0101000111";
			wait until rising_edge(clk);

			PA <= "0111011110";
			PB <= "1010000101";
			wait until rising_edge(clk);

			PA <= "0001011010";
			PB <= "0001111010";
			wait until rising_edge(clk);

			PA <= "1101110011";
			PB <= "1100010101";
			wait until rising_edge(clk);

			PA <= "0100010001";
			PB <= "0010100011";
			wait until rising_edge(clk);

			PA <= "0010101011";
			PB <= "0001101100";
			wait until rising_edge(clk);

			PA <= "1010000101";
			PB <= "0000001110";
			wait until rising_edge(clk);

			PA <= "0010100101";
			PB <= "1011111100";
			wait until rising_edge(clk);

			PA <= "1110010101";
			PB <= "1111010110";
			wait until rising_edge(clk);

			PA <= "0000000100";
			PB <= "0100011101";
			wait until rising_edge(clk);

			PA <= "1011011011";
			PB <= "0111001001";
			wait until rising_edge(clk);

			PA <= "1000111000";
			PB <= "1101010001";
			wait until rising_edge(clk);

			PA <= "1011110111";
			PB <= "1011001001";
			wait until rising_edge(clk);

			PA <= "0001110111";
			PB <= "1010000001";
			wait until rising_edge(clk);

			PA <= "0001001010";
			PB <= "0101101101";
			wait until rising_edge(clk);

			PA <= "0010100010";
			PB <= "0110101110";
			wait until rising_edge(clk);

			PA <= "0100010100";
			PB <= "1110101111";
			wait until rising_edge(clk);

			PA <= "1111000011";
			PB <= "0001110010";
			wait until rising_edge(clk);

			PA <= "0111001000";
			PB <= "1000001110";
			wait until rising_edge(clk);

			PA <= "0000000101";
			PB <= "1101001110";
			wait until rising_edge(clk);

			PA <= "0100000011";
			PB <= "1010010001";
			wait until rising_edge(clk);

			PA <= "0111111000";
			PB <= "0101101001";
			wait until rising_edge(clk);

			PA <= "0000110011";
			PB <= "0001011100";
			wait until rising_edge(clk);

			PA <= "1101000101";
			PB <= "1101001110";
			wait until rising_edge(clk);

			PA <= "0110101010";
			PB <= "0000110000";
			wait until rising_edge(clk);

			PA <= "0101101000";
			PB <= "1110001010";
			wait until rising_edge(clk);

			PA <= "0011111101";
			PB <= "1001001101";
			wait until rising_edge(clk);

			PA <= "1000100000";
			PB <= "0110000110";
			wait until rising_edge(clk);

			PA <= "0000010110";
			PB <= "0111001100";
			wait until rising_edge(clk);

			PA <= "0011011100";
			PB <= "1001101111";
			wait until rising_edge(clk);

			PA <= "1010010101";
			PB <= "1000011000";
			wait until rising_edge(clk);

			PA <= "1100000110";
			PB <= "0000011000";
			wait until rising_edge(clk);

			PA <= "0110111010";
			PB <= "1110011001";
			wait until rising_edge(clk);

			PA <= "1010100111";
			PB <= "1001000001";
			wait until rising_edge(clk);

			PA <= "1010100011";
			PB <= "0100110010";
			wait until rising_edge(clk);

			PA <= "1100110100";
			PB <= "0110100000";
			wait until rising_edge(clk);

			PA <= "1101010101";
			PB <= "1001110100";
			wait until rising_edge(clk);

			PA <= "1001010010";
			PB <= "0011101111";
			wait until rising_edge(clk);

			PA <= "0011101111";
			PB <= "1110011111";
			wait until rising_edge(clk);

			PA <= "1010111001";
			PB <= "0010010010";
			wait until rising_edge(clk);

			PA <= "0100100010";
			PB <= "1101110011";
			wait until rising_edge(clk);

			PA <= "1000011001";
			PB <= "1100100100";
			wait until rising_edge(clk);

			PA <= "1011110111";
			PB <= "1101010010";
			wait until rising_edge(clk);

			PA <= "0000111001";
			PB <= "1000011000";
			wait until rising_edge(clk);

			PA <= "1011000110";
			PB <= "0101100110";
			wait until rising_edge(clk);

			PA <= "1110001000";
			PB <= "1000100100";
			wait until rising_edge(clk);

			PA <= "0110111011";
			PB <= "1110100110";
			wait until rising_edge(clk);

			PA <= "1101100110";
			PB <= "1000010111";
			wait until rising_edge(clk);

			PA <= "1100000000";
			PB <= "1100111010";
			wait until rising_edge(clk);


------------------------------------------


			PA <= "0000100011";
			PB <= "1111011100";
			wait until rising_edge(clk);

			PA <= "0101101011";
			PB <= "1000101110";
			wait until rising_edge(clk);

			PA <= "0101010110";
			PB <= "0110000011";
			wait until rising_edge(clk);

			PA <= "0100011000";
			PB <= "1000111001";
			wait until rising_edge(clk);

			PA <= "0010001101";
			PB <= "1110100011";
			wait until rising_edge(clk);

			PA <= "1000000110";
			PB <= "1010100001";
			wait until rising_edge(clk);

			PA <= "1011001101";
			PB <= "0111111111";
			wait until rising_edge(clk);

			PA <= "1010011111";
			PB <= "0110100011";
			wait until rising_edge(clk);

			PA <= "0101100010";
			PB <= "0000000101";
			wait until rising_edge(clk);

			PA <= "1011000110";
			PB <= "0110001101";
			wait until rising_edge(clk);

			PA <= "1101100000";
			PB <= "1011010100";
			wait until rising_edge(clk);

			PA <= "0011110011";
			PB <= "1101110010";
			wait until rising_edge(clk);

			PA <= "0001001001";
			PB <= "0001110010";
			wait until rising_edge(clk);

			PA <= "1011001101";
			PB <= "0101101010";
			wait until rising_edge(clk);

			PA <= "0110001100";
			PB <= "1100100001";
			wait until rising_edge(clk);

			PA <= "0111111010";
			PB <= "1011111111";
			wait until rising_edge(clk);

			PA <= "1000010011";
			PB <= "1001100010";
			wait until rising_edge(clk);

			PA <= "1101101110";
			PB <= "1101101000";
			wait until rising_edge(clk);

			PA <= "1010111000";
			PB <= "1001000000";
			wait until rising_edge(clk);

			PA <= "1110111001";
			PB <= "0000000011";
			wait until rising_edge(clk);

			PA <= "1001100011";
			PB <= "0110100111";
			wait until rising_edge(clk);

			PA <= "0010111000";
			PB <= "0110110000";
			wait until rising_edge(clk);

			PA <= "1001101001";
			PB <= "0010001000";
			wait until rising_edge(clk);

			PA <= "1100111101";
			PB <= "1110110011";
			wait until rising_edge(clk);

			PA <= "0010100010";
			PB <= "1110100000";
			wait until rising_edge(clk);

			PA <= "1000101110";
			PB <= "1111111101";
			wait until rising_edge(clk);

			PA <= "1101110101";
			PB <= "0011111101";
			wait until rising_edge(clk);

			PA <= "1111000000";
			PB <= "0001101101";
			wait until rising_edge(clk);

			PA <= "1111111001";
			PB <= "1111110010";
			wait until rising_edge(clk);

			PA <= "1000101000";
			PB <= "0101001000";
			wait until rising_edge(clk);

			PA <= "1110010011";
			PB <= "0011111010";
			wait until rising_edge(clk);

			PA <= "1110011011";
			PB <= "0110001100";
			wait until rising_edge(clk);

			PA <= "1011011010";
			PB <= "1100101000";
			wait until rising_edge(clk);

			PA <= "1100111101";
			PB <= "0001011000";
			wait until rising_edge(clk);

			PA <= "1100101111";
			PB <= "1100001000";
			wait until rising_edge(clk);

			PA <= "1101001011";
			PB <= "0100000010";
			wait until rising_edge(clk);

			PA <= "0010001100";
			PB <= "0100000011";
			wait until rising_edge(clk);

			PA <= "0110000010";
			PB <= "0100101011";
			wait until rising_edge(clk);

			PA <= "1001110100";
			PB <= "1111100011";
			wait until rising_edge(clk);

			PA <= "0100101000";
			PB <= "0011111010";
			wait until rising_edge(clk);

			PA <= "1110010110";
			PB <= "1000001101";
			wait until rising_edge(clk);

			PA <= "0110011001";
			PB <= "1100111100";
			wait until rising_edge(clk);

			PA <= "0011111100";
			PB <= "1101001000";
			wait until rising_edge(clk);

			PA <= "1111010100";
			PB <= "0000100001";
			wait until rising_edge(clk);

			PA <= "1001000001";
			PB <= "0001110000";
			wait until rising_edge(clk);

			PA <= "1111101011";
			PB <= "1111111111";
			wait until rising_edge(clk);

			PA <= "1000010010";
			PB <= "0011001010";
			wait until rising_edge(clk);

			PA <= "0000000001";
			PB <= "0110001001";
			wait until rising_edge(clk);

			PA <= "0010000101";
			PB <= "0110111101";
			wait until rising_edge(clk);

			PA <= "0010110011";
			PB <= "0101101100";
			wait until rising_edge(clk);

			PA <= "1100111001";
			PB <= "0010111000";
			wait until rising_edge(clk);

			PA <= "0100010010";
			PB <= "0000000110";
			wait until rising_edge(clk);

			PA <= "1100001010";
			PB <= "0010010111";
			wait until rising_edge(clk);

			PA <= "1100110011";
			PB <= "1000001011";
			wait until rising_edge(clk);

			PA <= "0010101001";
			PB <= "0011000111";
			wait until rising_edge(clk);

			PA <= "0010110001";
			PB <= "1001101010";
			wait until rising_edge(clk);

			PA <= "1000000110";
			PB <= "0101101011";
			wait until rising_edge(clk);

			PA <= "1001100110";
			PB <= "0101000011";
			wait until rising_edge(clk);

			PA <= "0011111110";
			PB <= "0000100011";
			wait until rising_edge(clk);

			PA <= "1000011000";
			PB <= "0100110110";
			wait until rising_edge(clk);

			PA <= "0010111010";
			PB <= "1000001100";
			wait until rising_edge(clk);

			PA <= "0001101010";
			PB <= "1101010100";
			wait until rising_edge(clk);

			PA <= "1000000110";
			PB <= "1101010001";
			wait until rising_edge(clk);

			PA <= "1011100011";
			PB <= "0101101110";
			wait until rising_edge(clk);

			PA <= "1010111001";
			PB <= "1110010010";
			wait until rising_edge(clk);

			PA <= "0000110111";
			PB <= "0110101100";
			wait until rising_edge(clk);

			PA <= "0110111010";
			PB <= "0110010111";
			wait until rising_edge(clk);

			PA <= "1111111001";
			PB <= "1110111001";
			wait until rising_edge(clk);

			PA <= "0010110111";
			PB <= "1010011101";
			wait until rising_edge(clk);

			PA <= "0100100101";
			PB <= "1000011001";
			wait until rising_edge(clk);

			PA <= "1101110010";
			PB <= "0001001000";
			wait until rising_edge(clk);

			PA <= "1000111100";
			PB <= "1110010111";
			wait until rising_edge(clk);

			PA <= "1010010011";
			PB <= "0010111000";
			wait until rising_edge(clk);

			PA <= "0110100001";
			PB <= "1010110011";
			wait until rising_edge(clk);

			PA <= "1100000111";
			PB <= "0010010011";
			wait until rising_edge(clk);

			PA <= "0111101000";
			PB <= "1101001111";
			wait until rising_edge(clk);

			PA <= "0011001000";
			PB <= "0100001000";
			wait until rising_edge(clk);

			PA <= "0000101101";
			PB <= "1100111010";
			wait until rising_edge(clk);

			PA <= "0011000100";
			PB <= "1011001110";
			wait until rising_edge(clk);

			PA <= "1100100100";
			PB <= "1100011110";
			wait until rising_edge(clk);

			PA <= "0101110011";
			PB <= "0111011000";
			wait until rising_edge(clk);

			PA <= "1000111010";
			PB <= "0100010101";
			wait until rising_edge(clk);

			PA <= "1011010110";
			PB <= "1000010111";
			wait until rising_edge(clk);

			PA <= "0111001001";
			PB <= "1000000000";
			wait until rising_edge(clk);

			PA <= "1111111111";
			PB <= "0011010001";
			wait until rising_edge(clk);

			PA <= "0010100000";
			PB <= "0011101111";
			wait until rising_edge(clk);

			PA <= "1110010011";
			PB <= "1000110111";
			wait until rising_edge(clk);

			PA <= "0110010110";
			PB <= "1010010001";
			wait until rising_edge(clk);

			PA <= "1000101001";
			PB <= "0111001001";
			wait until rising_edge(clk);

			PA <= "1011011010";
			PB <= "0101110001";
			wait until rising_edge(clk);

			PA <= "1101110010";
			PB <= "0100001101";
			wait until rising_edge(clk);

			PA <= "1100011000";
			PB <= "0001101010";
			wait until rising_edge(clk);

			PA <= "0100110010";
			PB <= "0101000010";
			wait until rising_edge(clk);

			PA <= "1101100010";
			PB <= "1100101110";
			wait until rising_edge(clk);

			PA <= "1000111011";
			PB <= "0001110101";
			wait until rising_edge(clk);

			PA <= "1001110111";
			PB <= "1010100101";
			wait until rising_edge(clk);

			PA <= "1001010100";
			PB <= "0011011110";
			wait until rising_edge(clk);

			PA <= "0000100011";
			PB <= "1111010000";
			wait until rising_edge(clk);

			PA <= "1011100110";
			PB <= "0110110011";
			wait until rising_edge(clk);

			PA <= "1100111010";
			PB <= "0001000000";
			wait until rising_edge(clk);

			PA <= "1011000001";
			PB <= "1001110010";
			wait until rising_edge(clk);

			PA <= "1011000110";
			PB <= "0010111010";
			wait until rising_edge(clk);

			PA <= "1110111110";
			PB <= "1100111000";
			wait until rising_edge(clk);

			PA <= "0110011101";
			PB <= "1001110001";
			wait until rising_edge(clk);

			PA <= "0011110010";
			PB <= "0100011011";
			wait until rising_edge(clk);

			PA <= "1100000011";
			PB <= "1011111010";
			wait until rising_edge(clk);

			PA <= "0001010111";
			PB <= "0100111110";
			wait until rising_edge(clk);

			PA <= "1111101101";
			PB <= "1011110101";
			wait until rising_edge(clk);

			PA <= "1011111011";
			PB <= "1011000111";
			wait until rising_edge(clk);

			PA <= "0010000110";
			PB <= "0101001100";
			wait until rising_edge(clk);

			PA <= "1111101010";
			PB <= "0000110001";
			wait until rising_edge(clk);

			PA <= "1001111101";
			PB <= "0100001101";
			wait until rising_edge(clk);

			PA <= "0110001010";
			PB <= "0111001010";
			wait until rising_edge(clk);

			PA <= "0110110000";
			PB <= "1101001101";
			wait until rising_edge(clk);

			PA <= "0010101100";
			PB <= "1000011101";
			wait until rising_edge(clk);

			PA <= "0011100010";
			PB <= "1010010010";
			wait until rising_edge(clk);

			PA <= "0011110111";
			PB <= "0000110011";
			wait until rising_edge(clk);

			PA <= "1101111001";
			PB <= "0101011010";
			wait until rising_edge(clk);

			PA <= "1100110001";
			PB <= "1101001000";
			wait until rising_edge(clk);

			PA <= "1100101000";
			PB <= "0011000000";
			wait until rising_edge(clk);

			PA <= "1111001010";
			PB <= "1011010110";
			wait until rising_edge(clk);


------------------------------------------


			PA <= "1101100101";
			PB <= "1010110011";
			wait until rising_edge(clk);

			PA <= "1111100000";
			PB <= "0110000001";
			wait until rising_edge(clk);

			PA <= "0100000001";
			PB <= "1111100111";
			wait until rising_edge(clk);

			PA <= "0110101111";
			PB <= "1001101001";
			wait until rising_edge(clk);

			PA <= "1100110101";
			PB <= "1001011001";
			wait until rising_edge(clk);

			PA <= "0011100011";
			PB <= "0011101001";
			wait until rising_edge(clk);

			PA <= "0000010101";
			PB <= "0101000000";
			wait until rising_edge(clk);

			PA <= "1101001011";
			PB <= "1011101001";
			wait until rising_edge(clk);

			PA <= "1111000010";
			PB <= "0010011101";
			wait until rising_edge(clk);

			PA <= "1001010001";
			PB <= "0000111111";
			wait until rising_edge(clk);

			PA <= "0110111011";
			PB <= "0010101111";
			wait until rising_edge(clk);

			PA <= "1010110110";
			PB <= "0101101110";
			wait until rising_edge(clk);

			PA <= "1110101010";
			PB <= "0000101011";
			wait until rising_edge(clk);

			PA <= "0000011100";
			PB <= "0000001110";
			wait until rising_edge(clk);

			PA <= "1010001111";
			PB <= "0010100010";
			wait until rising_edge(clk);

			PA <= "0101001101";
			PB <= "0010110101";
			wait until rising_edge(clk);

			PA <= "0000111010";
			PB <= "1101011001";
			wait until rising_edge(clk);

			PA <= "0011110001";
			PB <= "1001111100";
			wait until rising_edge(clk);

			PA <= "0101011011";
			PB <= "1010010100";
			wait until rising_edge(clk);

			PA <= "1011111100";
			PB <= "1001011110";
			wait until rising_edge(clk);

			PA <= "0110110001";
			PB <= "0111010000";
			wait until rising_edge(clk);

			PA <= "1000001100";
			PB <= "1011101101";
			wait until rising_edge(clk);

			PA <= "1110011101";
			PB <= "1000011100";
			wait until rising_edge(clk);

			PA <= "0001101101";
			PB <= "1101000100";
			wait until rising_edge(clk);

			PA <= "1000111101";
			PB <= "0000000011";
			wait until rising_edge(clk);

			PA <= "1110111100";
			PB <= "0100110111";
			wait until rising_edge(clk);

			PA <= "1010010010";
			PB <= "1000110101";
			wait until rising_edge(clk);

			PA <= "1001101001";
			PB <= "0100100100";
			wait until rising_edge(clk);

			PA <= "0000000001";
			PB <= "0111011101";
			wait until rising_edge(clk);

			PA <= "1111010000";
			PB <= "0011110100";
			wait until rising_edge(clk);

			PA <= "0111010001";
			PB <= "0011111000";
			wait until rising_edge(clk);

			PA <= "1110000101";
			PB <= "1110000101";
			wait until rising_edge(clk);

			PA <= "0110100111";
			PB <= "1010101001";
			wait until rising_edge(clk);

			PA <= "1011010000";
			PB <= "1000101011";
			wait until rising_edge(clk);

			PA <= "1010001111";
			PB <= "1100101010";
			wait until rising_edge(clk);

			PA <= "0110110100";
			PB <= "1010001111";
			wait until rising_edge(clk);

			PA <= "1011001100";
			PB <= "1111001111";
			wait until rising_edge(clk);

			PA <= "0001010100";
			PB <= "0110110011";
			wait until rising_edge(clk);

			PA <= "1011100000";
			PB <= "0110100000";
			wait until rising_edge(clk);

			PA <= "1110111100";
			PB <= "1010001010";
			wait until rising_edge(clk);

			PA <= "1010111101";
			PB <= "1000111111";
			wait until rising_edge(clk);

			PA <= "0111110001";
			PB <= "0110000111";
			wait until rising_edge(clk);

			PA <= "0010100010";
			PB <= "1100001000";
			wait until rising_edge(clk);

			PA <= "1111001101";
			PB <= "0100011010";
			wait until rising_edge(clk);

			PA <= "1111100110";
			PB <= "0101111011";
			wait until rising_edge(clk);

			PA <= "1101010101";
			PB <= "1010110011";
			wait until rising_edge(clk);

			PA <= "1011110011";
			PB <= "1010000010";
			wait until rising_edge(clk);

			PA <= "1110001001";
			PB <= "0001111000";
			wait until rising_edge(clk);

			PA <= "1000100011";
			PB <= "0011101001";
			wait until rising_edge(clk);

			PA <= "1001100111";
			PB <= "1000001001";
			wait until rising_edge(clk);

			PA <= "0000000111";
			PB <= "1100101000";
			wait until rising_edge(clk);

			PA <= "0111010100";
			PB <= "0110101010";
			wait until rising_edge(clk);

			PA <= "1110001101";
			PB <= "0001010101";
			wait until rising_edge(clk);

			PA <= "0101100001";
			PB <= "1011001110";
			wait until rising_edge(clk);

			PA <= "0111010011";
			PB <= "0011111110";
			wait until rising_edge(clk);

			PA <= "1010011011";
			PB <= "1011100001";
			wait until rising_edge(clk);

			PA <= "0100101101";
			PB <= "1011011110";
			wait until rising_edge(clk);

			PA <= "1000001010";
			PB <= "1001111110";
			wait until rising_edge(clk);

			PA <= "0001110011";
			PB <= "1111111011";
			wait until rising_edge(clk);

			PA <= "1010111111";
			PB <= "1000010111";
			wait until rising_edge(clk);

			PA <= "1110110101";
			PB <= "0000111011";
			wait until rising_edge(clk);

			PA <= "1100011000";
			PB <= "0110100001";
			wait until rising_edge(clk);

			PA <= "1101110100";
			PB <= "0111111110";
			wait until rising_edge(clk);

			PA <= "1001011000";
			PB <= "0001101110";
			wait until rising_edge(clk);

			PA <= "1000000011";
			PB <= "1011110111";
			wait until rising_edge(clk);

			PA <= "1101001110";
			PB <= "1011101011";
			wait until rising_edge(clk);

			PA <= "0101101010";
			PB <= "1111010001";
			wait until rising_edge(clk);

			PA <= "0110111101";
			PB <= "0110000001";
			wait until rising_edge(clk);

			PA <= "1001100010";
			PB <= "0000111011";
			wait until rising_edge(clk);

			PA <= "0111001110";
			PB <= "1011100111";
			wait until rising_edge(clk);

			PA <= "0001000100";
			PB <= "1100101111";
			wait until rising_edge(clk);

			PA <= "0101001100";
			PB <= "0001100111";
			wait until rising_edge(clk);

			PA <= "1000000001";
			PB <= "1101000000";
			wait until rising_edge(clk);

			PA <= "0110101001";
			PB <= "1110101100";
			wait until rising_edge(clk);

			PA <= "1010111111";
			PB <= "1001100000";
			wait until rising_edge(clk);

			PA <= "0001010111";
			PB <= "1010011111";
			wait until rising_edge(clk);

			PA <= "0101000111";
			PB <= "0011001001";
			wait until rising_edge(clk);

			PA <= "1011001111";
			PB <= "1001101001";
			wait until rising_edge(clk);

			PA <= "1000011111";
			PB <= "0000111110";
			wait until rising_edge(clk);

			PA <= "1111010110";
			PB <= "0101001011";
			wait until rising_edge(clk);

			PA <= "1000001111";
			PB <= "1000000001";
			wait until rising_edge(clk);

			PA <= "1101111001";
			PB <= "0010001011";
			wait until rising_edge(clk);

			PA <= "1011010101";
			PB <= "0110000110";
			wait until rising_edge(clk);

			PA <= "0111011110";
			PB <= "1011010010";
			wait until rising_edge(clk);

			PA <= "0100100111";
			PB <= "0010100110";
			wait until rising_edge(clk);

			PA <= "0110010001";
			PB <= "0000011110";
			wait until rising_edge(clk);

			PA <= "0111001000";
			PB <= "1001001100";
			wait until rising_edge(clk);

			PA <= "0111001011";
			PB <= "1000110000";
			wait until rising_edge(clk);

			PA <= "1110010111";
			PB <= "1111000100";
			wait until rising_edge(clk);

			PA <= "1110110111";
			PB <= "1100000110";
			wait until rising_edge(clk);

			PA <= "0001010010";
			PB <= "0001001000";
			wait until rising_edge(clk);

			PA <= "1110100101";
			PB <= "1010100001";
			wait until rising_edge(clk);

			PA <= "1010000110";
			PB <= "1000001110";
			wait until rising_edge(clk);

			PA <= "1110110100";
			PB <= "1000110111";
			wait until rising_edge(clk);

			PA <= "1001010100";
			PB <= "0001010011";
			wait until rising_edge(clk);

			PA <= "1001010111";
			PB <= "1000001110";
			wait until rising_edge(clk);

			PA <= "1100111111";
			PB <= "1111001011";
			wait until rising_edge(clk);

			PA <= "1101111110";
			PB <= "0101011100";
			wait until rising_edge(clk);

			PA <= "1010101110";
			PB <= "1010111001";
			wait until rising_edge(clk);

			PA <= "1010110110";
			PB <= "1111110111";
			wait until rising_edge(clk);

			PA <= "0010110111";
			PB <= "0001101100";
			wait until rising_edge(clk);

			PA <= "1110010101";
			PB <= "0100000110";
			wait until rising_edge(clk);

			PA <= "1100000100";
			PB <= "0101001011";
			wait until rising_edge(clk);

			PA <= "0100101101";
			PB <= "0111011010";
			wait until rising_edge(clk);

			PA <= "0111110001";
			PB <= "1110101001";
			wait until rising_edge(clk);

			PA <= "1000000101";
			PB <= "1110000101";
			wait until rising_edge(clk);

			PA <= "0110110101";
			PB <= "0101100110";
			wait until rising_edge(clk);

			PA <= "1011110100";
			PB <= "0001000001";
			wait until rising_edge(clk);

			PA <= "0100001110";
			PB <= "1111110110";
			wait until rising_edge(clk);

			PA <= "1001101100";
			PB <= "0101100011";
			wait until rising_edge(clk);

			PA <= "1111100101";
			PB <= "0000110010";
			wait until rising_edge(clk);

			PA <= "1101100001";
			PB <= "1001000001";
			wait until rising_edge(clk);

			PA <= "0011100000";
			PB <= "0001001000";
			wait until rising_edge(clk);

			PA <= "0000101101";
			PB <= "1001111110";
			wait until rising_edge(clk);

			PA <= "1101101010";
			PB <= "0010000101";
			wait until rising_edge(clk);

			PA <= "0010101000";
			PB <= "1111101010";
			wait until rising_edge(clk);

			PA <= "0011010111";
			PB <= "0001111110";
			wait until rising_edge(clk);

			PA <= "0010010100";
			PB <= "1001100100";
			wait until rising_edge(clk);

			PA <= "1011010011";
			PB <= "0010111101";
			wait until rising_edge(clk);

			PA <= "0100100100";
			PB <= "1101001001";
			wait until rising_edge(clk);

			PA <= "0110101011";
			PB <= "1110001001";
			wait until rising_edge(clk);


------------------------------------------


			PA <= "0000001001";
			PB <= "1100110111";
			wait until rising_edge(clk);

			PA <= "0000001101";
			PB <= "0101000101";
			wait until rising_edge(clk);

			PA <= "1011111011";
			PB <= "1001011100";
			wait until rising_edge(clk);

			PA <= "0000100000";
			PB <= "0110010000";
			wait until rising_edge(clk);

			PA <= "1000111010";
			PB <= "0111000111";
			wait until rising_edge(clk);

			PA <= "1111100100";
			PB <= "1001101000";
			wait until rising_edge(clk);

			PA <= "0111011010";
			PB <= "1011011101";
			wait until rising_edge(clk);

			PA <= "1011100010";
			PB <= "1100110101";
			wait until rising_edge(clk);

			PA <= "0101111101";
			PB <= "0000010101";
			wait until rising_edge(clk);

			PA <= "1100010110";
			PB <= "1110010000";
			wait until rising_edge(clk);

			PA <= "1011101000";
			PB <= "1001111000";
			wait until rising_edge(clk);

			PA <= "0110100110";
			PB <= "1111100110";
			wait until rising_edge(clk);

			PA <= "0110101001";
			PB <= "1000001011";
			wait until rising_edge(clk);

			PA <= "0010011011";
			PB <= "0001010001";
			wait until rising_edge(clk);

			PA <= "0110110101";
			PB <= "1001000001";
			wait until rising_edge(clk);

			PA <= "0100010100";
			PB <= "0110001010";
			wait until rising_edge(clk);

			PA <= "0101000100";
			PB <= "0100000000";
			wait until rising_edge(clk);

			PA <= "0011011011";
			PB <= "1100000100";
			wait until rising_edge(clk);

			PA <= "1011111101";
			PB <= "1101000001";
			wait until rising_edge(clk);

			PA <= "1101010111";
			PB <= "0100111000";
			wait until rising_edge(clk);

			PA <= "0010111100";
			PB <= "0101100111";
			wait until rising_edge(clk);

			PA <= "0101110011";
			PB <= "1110000001";
			wait until rising_edge(clk);

			PA <= "0000011010";
			PB <= "0010101010";
			wait until rising_edge(clk);

			PA <= "0100010001";
			PB <= "1100011111";
			wait until rising_edge(clk);

			PA <= "0001011100";
			PB <= "0010011011";
			wait until rising_edge(clk);

			PA <= "1011101001";
			PB <= "0011100001";
			wait until rising_edge(clk);

			PA <= "1000010000";
			PB <= "0101001111";
			wait until rising_edge(clk);

			PA <= "0011000111";
			PB <= "1111101010";
			wait until rising_edge(clk);

			PA <= "0010100110";
			PB <= "1001101000";
			wait until rising_edge(clk);

			PA <= "0110000001";
			PB <= "1011111000";
			wait until rising_edge(clk);

			PA <= "0000000101";
			PB <= "0101111010";
			wait until rising_edge(clk);

			PA <= "0100111110";
			PB <= "1110010101";
			wait until rising_edge(clk);

			PA <= "0011011101";
			PB <= "0011000110";
			wait until rising_edge(clk);

			PA <= "1101110000";
			PB <= "1111001110";
			wait until rising_edge(clk);

			PA <= "0111110110";
			PB <= "1010101100";
			wait until rising_edge(clk);

			PA <= "0110111001";
			PB <= "0000101011";
			wait until rising_edge(clk);

			PA <= "1001101101";
			PB <= "1111110100";
			wait until rising_edge(clk);

			PA <= "0111001011";
			PB <= "0110010111";
			wait until rising_edge(clk);

			PA <= "0111100000";
			PB <= "0001011011";
			wait until rising_edge(clk);

			PA <= "1010010001";
			PB <= "0011001101";
			wait until rising_edge(clk);

			PA <= "0100001111";
			PB <= "1011110000";
			wait until rising_edge(clk);

			PA <= "1011001011";
			PB <= "1101111111";
			wait until rising_edge(clk);

			PA <= "0000101001";
			PB <= "0010001101";
			wait until rising_edge(clk);

			PA <= "0011110001";
			PB <= "1111010001";
			wait until rising_edge(clk);

			PA <= "1111010011";
			PB <= "1011001111";
			wait until rising_edge(clk);

			PA <= "1010010000";
			PB <= "1101101011";
			wait until rising_edge(clk);

			PA <= "1000000110";
			PB <= "0000000100";
			wait until rising_edge(clk);

			PA <= "0010111101";
			PB <= "0000110110";
			wait until rising_edge(clk);

			PA <= "1101000011";
			PB <= "0100111001";
			wait until rising_edge(clk);

			PA <= "1010110111";
			PB <= "0010010000";
			wait until rising_edge(clk);

			PA <= "1111100001";
			PB <= "1011001010";
			wait until rising_edge(clk);

			PA <= "1000011001";
			PB <= "1010001010";
			wait until rising_edge(clk);

			PA <= "1010110111";
			PB <= "0110000011";
			wait until rising_edge(clk);

			PA <= "0001011001";
			PB <= "0001100100";
			wait until rising_edge(clk);

			PA <= "1001101101";
			PB <= "0101111111";
			wait until rising_edge(clk);

			PA <= "0101000011";
			PB <= "1110111011";
			wait until rising_edge(clk);

			PA <= "1000110100";
			PB <= "1011101010";
			wait until rising_edge(clk);

			PA <= "1000100011";
			PB <= "0100111101";
			wait until rising_edge(clk);

			PA <= "0010101110";
			PB <= "0101101101";
			wait until rising_edge(clk);

			PA <= "1100000011";
			PB <= "0011001100";
			wait until rising_edge(clk);

			PA <= "0000111111";
			PB <= "0100001101";
			wait until rising_edge(clk);

			PA <= "1010011001";
			PB <= "0010111101";
			wait until rising_edge(clk);

			PA <= "0110011100";
			PB <= "0010010110";
			wait until rising_edge(clk);

			PA <= "0011100000";
			PB <= "0111000110";
			wait until rising_edge(clk);

			PA <= "0100001110";
			PB <= "1011001001";
			wait until rising_edge(clk);

			PA <= "0011011001";
			PB <= "1110011101";
			wait until rising_edge(clk);

			PA <= "0011001100";
			PB <= "1111101001";
			wait until rising_edge(clk);

			PA <= "1000110010";
			PB <= "0001100010";
			wait until rising_edge(clk);

			PA <= "0111000011";
			PB <= "1000010100";
			wait until rising_edge(clk);

			PA <= "0011010111";
			PB <= "0011111000";
			wait until rising_edge(clk);

			PA <= "0111011001";
			PB <= "1101100000";
			wait until rising_edge(clk);

			PA <= "1110110001";
			PB <= "1101010110";
			wait until rising_edge(clk);

			PA <= "1000001001";
			PB <= "1110011101";
			wait until rising_edge(clk);

			PA <= "1010101000";
			PB <= "1001100111";
			wait until rising_edge(clk);

			PA <= "1011000111";
			PB <= "0001000111";
			wait until rising_edge(clk);

			PA <= "1000100000";
			PB <= "0111101100";
			wait until rising_edge(clk);

			PA <= "1100111000";
			PB <= "0110010001";
			wait until rising_edge(clk);

			PA <= "0000110110";
			PB <= "0110011000";
			wait until rising_edge(clk);

			PA <= "1011100011";
			PB <= "1111011010";
			wait until rising_edge(clk);

			PA <= "0111100101";
			PB <= "1001100110";
			wait until rising_edge(clk);

			PA <= "1010011101";
			PB <= "1011000001";
			wait until rising_edge(clk);

			PA <= "1110011110";
			PB <= "1000000111";
			wait until rising_edge(clk);

			PA <= "0010010011";
			PB <= "0101110010";
			wait until rising_edge(clk);

			PA <= "0110100111";
			PB <= "1111111000";
			wait until rising_edge(clk);

			PA <= "0110000011";
			PB <= "0100110000";
			wait until rising_edge(clk);

			PA <= "0101001010";
			PB <= "0101100110";
			wait until rising_edge(clk);

			PA <= "1000010011";
			PB <= "1000101010";
			wait until rising_edge(clk);

			PA <= "1010000001";
			PB <= "1101000110";
			wait until rising_edge(clk);

			PA <= "0000101100";
			PB <= "0001001110";
			wait until rising_edge(clk);

			PA <= "0000000010";
			PB <= "1100010111";
			wait until rising_edge(clk);

			PA <= "1111000010";
			PB <= "0110011000";
			wait until rising_edge(clk);

			PA <= "1100011000";
			PB <= "1111011100";
			wait until rising_edge(clk);

			PA <= "1000001010";
			PB <= "1001000010";
			wait until rising_edge(clk);

			PA <= "0110111010";
			PB <= "1101111110";
			wait until rising_edge(clk);

			PA <= "1000110011";
			PB <= "0001101010";
			wait until rising_edge(clk);

			PA <= "1101000000";
			PB <= "1110001001";
			wait until rising_edge(clk);

			PA <= "0001100111";
			PB <= "1110001111";
			wait until rising_edge(clk);

			PA <= "1100101100";
			PB <= "0101010111";
			wait until rising_edge(clk);

			PA <= "0110010011";
			PB <= "1000110110";
			wait until rising_edge(clk);

			PA <= "1010111001";
			PB <= "1011000100";
			wait until rising_edge(clk);

			PA <= "0101010101";
			PB <= "0111010011";
			wait until rising_edge(clk);

			PA <= "0001100111";
			PB <= "1100110000";
			wait until rising_edge(clk);

			PA <= "1110000101";
			PB <= "1101001100";
			wait until rising_edge(clk);

			PA <= "1101011111";
			PB <= "1001000111";
			wait until rising_edge(clk);

			PA <= "1100000101";
			PB <= "0111011111";
			wait until rising_edge(clk);

			PA <= "0101010111";
			PB <= "0001110011";
			wait until rising_edge(clk);

			PA <= "0010010000";
			PB <= "0010001111";
			wait until rising_edge(clk);

			PA <= "1001101101";
			PB <= "0100010001";
			wait until rising_edge(clk);

			PA <= "0110010100";
			PB <= "0010100011";
			wait until rising_edge(clk);

			PA <= "1010100000";
			PB <= "1000000000";
			wait until rising_edge(clk);

			PA <= "1110001101";
			PB <= "0010011010";
			wait until rising_edge(clk);

			PA <= "1111001110";
			PB <= "1111111101";
			wait until rising_edge(clk);

			PA <= "0100110111";
			PB <= "1010010010";
			wait until rising_edge(clk);

			PA <= "0001101101";
			PB <= "1100011101";
			wait until rising_edge(clk);

			PA <= "0100110100";
			PB <= "0100100001";
			wait until rising_edge(clk);

			PA <= "1111001011";
			PB <= "0100011100";
			wait until rising_edge(clk);

			PA <= "0001011000";
			PB <= "1100001001";
			wait until rising_edge(clk);

			PA <= "0110100010";
			PB <= "1100011000";
			wait until rising_edge(clk);

			PA <= "0100100011";
			PB <= "1100101011";
			wait until rising_edge(clk);

			PA <= "0101001010";
			PB <= "1101000100";
			wait until rising_edge(clk);

			PA <= "0001101101";
			PB <= "0010110110";
			wait until rising_edge(clk);

			----------------------------------


	  		wait for 3330 ns;
	  		testing <= False;
	  		wait;
	  	end process;

	  	
	  	drive_rst: process
	  	begin
	  		reset <= '0';
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		reset <= '1';
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		reset <= '0';
	  		wait for 1500 ns;
	  		reset <= '1';
	  		wait for 330 ns;
	  		reset <= '0';
	  		wait for 2000 ns;
	  		reset <= '1';
	  		wait for 100 ns;
	  		reset <= '0';
	  		wait for 3000 ns;

	  		wait;
	  	end process;



	  	drive_en : process
	  	begin
	  		enable <= '1';
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		enable <= '0';
	  		wait until rising_edge(clk);
	  		wait until rising_edge(clk);
	  		enable <= '1';
	  		wait for 3000 ns;
	  		enable <= '0';
	  		wait for 200 ns;
	  		enable <= '1';
	  		wait for 2400 ns;
	  	end process;

end architecture;

